"""The reviewed selection inputs: areas, the generated catalogue, rules and policy.

Four artifacts under ``tests/``, each loaded and validated here:

* ``selection_areas.yaml`` (reviewed) names every *area*: an id, the one
  sentence describing what its tests check, and the module globs it owns.
* ``selection_catalogue.json`` (generated by
  ``scripts/generate-selection-catalogue.py``) lists every runnable test
  module with its areas and statically extracted metadata.  It is a pure
  function of the tree and the areas file, so a ratchet test regenerates it
  and compares bytes.
* ``selection_rules.yaml`` (reviewed) maps repository paths to what must
  run: global invalidators, scoped conftests, non-behavioural paths,
  ownership, source-scanning tests and the critical set.
* ``selection_policy.yaml`` (reviewed) pins the Jev model and the omission
  thresholds.

Nothing here runs a subprocess or touches the network: the caller supplies
the tracked-file list where one is needed.
"""

from __future__ import annotations

import ast
import dataclasses
import functools
import hashlib
import json
import math
import re
from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

from src.test_selection.discovery import pytest_rootdir, relative_modules

CATALOGUE_PATH = "tests/selection_catalogue.json"
AREAS_PATH = "tests/selection_areas.yaml"
RULES_PATH = "tests/selection_rules.yaml"
POLICY_PATH = "tests/selection_policy.yaml"
CATALOGUE_SCHEMA_VERSION = 1
GENERATOR_VERSION = 1
DEFAULT_MARKER_DESELECT = ("perf", "migration", "slow", "tmux", "integration")

AREAS_VERSION = 1
RULES_VERSION = 1
POLICY_VERSION = 1

#: Area ids are routing keys for Jev questions: kebab-case, bounded.
AREA_ID_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
AREA_ID_MAX = 40
#: An area description is one sentence sent to Jev with every question.
AREA_DESCRIPTION_MAX = 300

REGENERATE_HINT = "run `python scripts/generate-selection-catalogue.py`"


class CatalogueError(ValueError):
    """An artifact is unusable; ``problems`` holds one human line per problem."""

    def __init__(self, problems: Sequence[str]) -> None:
        self.problems = list(problems)
        super().__init__("; ".join(self.problems))


# --------------------------------------------------------------------------
# Globs


@functools.lru_cache(maxsize=4096)
def _glob_regex(pattern: str) -> re.Pattern[str]:
    out: list[str] = []
    i = 0
    while i < len(pattern):
        ch = pattern[i]
        if pattern.startswith("**/", i):
            out.append("(?:.*/)?")
            i += 3
        elif pattern.startswith("**", i):
            out.append(".*")
            i += 2
        elif ch == "*":
            out.append("[^/]*")
            i += 1
        elif ch == "?":
            out.append("[^/]")
            i += 1
        else:
            out.append(re.escape(ch))
            i += 1
    return re.compile("^" + "".join(out) + "$")


def match_glob(pattern: str, path: str) -> bool:
    """Anchored posix glob: ``**`` any depth (including none), ``*`` one segment, ``?`` one char."""
    return _glob_regex(pattern).match(path) is not None


def _any_match(patterns: Iterable[str], path: str) -> bool:
    return any(match_glob(p, path) for p in patterns)


def _is_glob(pattern: str) -> bool:
    return any(ch in pattern for ch in "*?")


def dotted_name(path: str) -> str | None:
    """``src/pkg/a.py`` -> ``src.pkg.a``; ``src/pkg/__init__.py`` -> ``src.pkg``; else ``None``."""
    if not path.endswith(".py"):
        return None
    parts = path[: -len(".py")].split("/")
    if parts[-1] == "__init__":
        parts = parts[:-1]
    if not parts or not all(p.isidentifier() for p in parts):
        return None
    return ".".join(parts)


def file_digest(path: Path) -> str:
    """``"sha256:<hex>"`` of the file's bytes."""
    return "sha256:" + hashlib.sha256(Path(path).read_bytes()).hexdigest()


def _text_digest(text: str) -> str:
    return "sha256:" + hashlib.sha256(text.encode("utf-8")).hexdigest()


def _load_yaml(path: Path) -> Any:
    try:
        return yaml.safe_load(Path(path).read_text(encoding="utf-8"))
    except OSError as exc:
        raise CatalogueError([f"{path}: unreadable ({exc.strerror or exc})"]) from exc
    except yaml.YAMLError as exc:
        raise CatalogueError([f"{path}: not valid YAML ({exc})"]) from exc


def _str_list(value: Any, where: str, problems: list[str], *, allow_empty: bool = False) -> tuple:
    if not isinstance(value, list) or not all(isinstance(v, str) and v for v in value):
        problems.append(f"{where}: must be a list of non-empty strings")
        return ()
    if not value and not allow_empty:
        problems.append(f"{where}: must not be empty")
    return tuple(value)


def _check_keys(obj: dict, allowed: set[str], where: str, problems: list[str]) -> None:
    unknown = sorted(set(obj) - allowed)
    if unknown:
        problems.append(f"{where}: unknown key(s) {', '.join(unknown)}")


# --------------------------------------------------------------------------
# Areas and the catalogue


@dataclass(frozen=True)
class AreaSpec:
    id: str
    description: str
    match: tuple[str, ...]


@dataclass(frozen=True)
class Area:
    id: str
    description: str
    modules: tuple[str, ...]


@dataclass(frozen=True)
class ModuleInfo:
    """What the catalogue knows about one runnable test module.

    ``imports``: dotted ``src`` names the module imports anywhere in its body
    (a test importing inside a function depends on that code just the same),
    plus ``src.pkg.name`` for ``from src.pkg import name`` when ``name`` is a
    submodule in the tree.  ``markers``: every ``pytest.mark.<name>`` in the
    file.  ``default_arm``: no :data:`DEFAULT_MARKER_DESELECT` marker is
    applied module-wide (``pytestmark``) — a hint, not the marker policy.
    """

    path: str
    areas: tuple[str, ...]
    imports: tuple[str, ...]
    markers: tuple[str, ...]
    summary: str
    default_arm: bool


@dataclass(frozen=True)
class Catalogue:
    schema_version: int
    generator_version: int
    roots: tuple[str, ...]
    areas: dict[str, Area]
    modules: dict[str, ModuleInfo]
    digest: str

    @property
    def universe(self) -> frozenset[str]:
        """Every catalogued module path."""
        return frozenset(self.modules)

    def modules_for_areas(self, area_ids: Iterable[str]) -> frozenset[str]:
        found: set[str] = set()
        for area_id in area_ids:
            area = self.areas.get(area_id)
            if area is not None:
                found.update(area.modules)
        return frozenset(found)

    def areas_for_module(self, path: str) -> tuple[str, ...]:
        info = self.modules.get(path)
        return info.areas if info is not None else ()

    def module_for_import(self, dotted: str) -> str | None:
        """``src.pkg.a`` -> ``src/pkg/a.py``: a pure string mapping.

        A package's own code lives in ``<pkg>/__init__.py``; without looking
        at the tree the two cannot be told apart, so callers holding a path
        compare :func:`dotted_name` of it instead.
        """
        if dotted != "src" and not dotted.startswith("src."):
            return None
        if not all(part.isidentifier() for part in dotted.split(".")):
            return None
        return dotted.replace(".", "/") + ".py"


def load_areas(path: Path) -> list[AreaSpec]:
    data = _load_yaml(path)
    problems: list[str] = []
    if not isinstance(data, dict):
        raise CatalogueError([f"{path}: expected a mapping with `version` and `areas`"])
    _check_keys(data, {"version", "areas"}, str(path), problems)
    if data.get("version") != AREAS_VERSION:
        problems.append(f"{path}: version must be {AREAS_VERSION}")
    raw = data.get("areas")
    if not isinstance(raw, list) or not raw:
        raise CatalogueError([*problems, f"{path}: `areas` must be a non-empty list"])
    specs: list[AreaSpec] = []
    seen: set[str] = set()
    for index, entry in enumerate(raw):
        where = f"{path}: areas[{index}]"
        if not isinstance(entry, dict):
            problems.append(f"{where}: must be a mapping")
            continue
        _check_keys(entry, {"id", "description", "match"}, where, problems)
        area_id = entry.get("id")
        if not isinstance(area_id, str) or not AREA_ID_RE.match(area_id):
            problems.append(f"{where}: id {area_id!r} is not kebab-case")
            continue
        where = f"{path}: area {area_id!r}"
        if len(area_id) > AREA_ID_MAX:
            problems.append(f"{where}: id longer than {AREA_ID_MAX} characters")
        if area_id in seen:
            problems.append(f"{where}: duplicate id")
        seen.add(area_id)
        description = entry.get("description")
        if not isinstance(description, str) or not description.strip():
            problems.append(f"{where}: description must be a non-empty string")
            description = ""
        elif len(description) > AREA_DESCRIPTION_MAX:
            problems.append(f"{where}: description longer than {AREA_DESCRIPTION_MAX} characters")
        match = _str_list(entry.get("match"), f"{where}: match", problems)
        specs.append(AreaSpec(area_id, description.strip(), match))
    if problems:
        raise CatalogueError(problems)
    return specs


def _resolves_to_module(rootdir: Path, dotted: str) -> bool:
    base = rootdir.joinpath(*dotted.split("."))
    return base.with_suffix(".py").is_file() or (base / "__init__.py").is_file()


def _is_src_name(name: str) -> bool:
    return name == "src" or name.startswith("src.")


def _module_info(rootdir: Path, rel: str, areas: tuple[str, ...]) -> ModuleInfo:
    source = (rootdir / rel).read_text(encoding="utf-8", errors="replace")
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return ModuleInfo(rel, areas, (), (), "", True)
    imports: set[str] = set()
    markers: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imports.update(a.name for a in node.names if _is_src_name(a.name))
        elif isinstance(node, ast.ImportFrom) and node.level == 0 and node.module:
            if _is_src_name(node.module):
                imports.add(node.module)
                for alias in node.names:
                    candidate = f"{node.module}.{alias.name}"
                    if alias.name != "*" and _resolves_to_module(rootdir, candidate):
                        imports.add(candidate)
        elif isinstance(node, ast.Attribute) and isinstance(node.value, ast.Attribute):
            inner = node.value
            if isinstance(inner.value, ast.Name) and (inner.value.id, inner.attr) == (
                "pytest",
                "mark",
            ):
                markers.add(node.attr)
    module_level: set[str] = set()
    for stmt in tree.body:
        if isinstance(stmt, ast.Assign):
            targets, value = stmt.targets, stmt.value
        elif isinstance(stmt, ast.AnnAssign) and stmt.value is not None:
            targets, value = [stmt.target], stmt.value
        else:
            continue
        if any(isinstance(t, ast.Name) and t.id == "pytestmark" for t in targets):
            module_level.update(n.attr for n in ast.walk(value) if isinstance(n, ast.Attribute))
    doc = (ast.get_docstring(tree) or "").strip()
    return ModuleInfo(
        path=rel,
        areas=areas,
        imports=tuple(sorted(imports)),
        markers=tuple(sorted(markers)),
        summary=doc.splitlines()[0].strip() if doc else "",
        default_arm=not (module_level & set(DEFAULT_MARKER_DESELECT)),
    )


def _catalogue_payload(catalogue: Catalogue, *, digest: str) -> dict[str, Any]:
    return {
        "schema_version": catalogue.schema_version,
        "generator_version": catalogue.generator_version,
        "roots": list(catalogue.roots),
        "areas": {
            a.id: {"description": a.description, "modules": list(a.modules)}
            for a in catalogue.areas.values()
        },
        "modules": {
            m.path: {
                "areas": list(m.areas),
                "imports": list(m.imports),
                "markers": list(m.markers),
                "summary": m.summary,
                "default_arm": m.default_arm,
            }
            for m in catalogue.modules.values()
        },
        "digest": digest,
    }


def _render(payload: dict[str, Any]) -> str:
    return json.dumps(payload, sort_keys=True, indent=2, ensure_ascii=False) + "\n"


def _digest_of(catalogue: Catalogue) -> str:
    return _text_digest(_render(_catalogue_payload(catalogue, digest="")))


def render_catalogue(catalogue: Catalogue) -> str:
    """Canonical JSON: sorted keys, two-space indent, trailing newline."""
    return _render(_catalogue_payload(catalogue, digest=catalogue.digest))


def build_catalogue(rootdir: Path, areas: list[AreaSpec]) -> Catalogue:
    """Catalogue every runnable module under pytest's ``testpaths``.

    Every module must match at least one area and every area at least one
    module; otherwise :class:`CatalogueError` lists each offender.
    """
    rootdir = rootdir.resolve()
    _, roots = pytest_rootdir(rootdir)
    modules = relative_modules(rootdir, roots)
    problems: list[str] = []
    ids = [a.id for a in areas]
    for dup in sorted({i for i in ids if ids.count(i) > 1}):
        problems.append(f"area {dup!r}: duplicate id")
    by_area: dict[str, list[str]] = {a.id: [] for a in areas}
    by_module: dict[str, list[str]] = {m: [] for m in modules}
    for area in areas:
        for module in modules:
            if _any_match(area.match, module):
                by_area[area.id].append(module)
                by_module[module].append(area.id)
    for module, owners in by_module.items():
        if not owners:
            problems.append(f"{module}: matches no area in {AREAS_PATH}")
    for area in areas:
        if not by_area[area.id]:
            problems.append(f"area {area.id!r}: matches no runnable module")
    if problems:
        raise CatalogueError(problems)
    area_objs = {
        a.id: Area(a.id, a.description, tuple(sorted(set(by_area[a.id]))))
        for a in sorted(areas, key=lambda a: a.id)
    }
    infos = {m: _module_info(rootdir, m, tuple(sorted(set(by_module[m])))) for m in modules}
    draft = Catalogue(
        CATALOGUE_SCHEMA_VERSION,
        GENERATOR_VERSION,
        tuple(r.relative_to(rootdir).as_posix() for r in roots),
        area_objs,
        infos,
        digest="",
    )
    return dataclasses.replace(draft, digest=_digest_of(draft))


def load_catalogue(path: Path) -> Catalogue:
    """Parse a committed catalogue; refuse a schema, generator or digest mismatch."""
    try:
        text = Path(path).read_text(encoding="utf-8")
    except OSError as exc:
        raise CatalogueError([f"{path}: unreadable ({exc.strerror or exc})"]) from exc
    return load_catalogue_text(text, source=str(path))


def load_catalogue_text(text: str, *, source: str) -> Catalogue:
    """Parse catalogue content from a Git blob with the same checks as a workspace file."""
    try:
        data = json.loads(text)
    except ValueError as exc:
        raise CatalogueError([f"{source}: not valid JSON ({exc})"]) from exc
    if not isinstance(data, dict):
        raise CatalogueError([f"{source}: expected a JSON object"])
    problems: list[str] = []
    if data.get("schema_version") != CATALOGUE_SCHEMA_VERSION:
        problems.append(
            f"{source}: schema_version {data.get('schema_version')!r} is not "
            f"{CATALOGUE_SCHEMA_VERSION}; {REGENERATE_HINT}"
        )
    if data.get("generator_version") != GENERATOR_VERSION:
        problems.append(
            f"{source}: generator_version {data.get('generator_version')!r} is not "
            f"{GENERATOR_VERSION}; {REGENERATE_HINT}"
        )
    if problems:
        raise CatalogueError(problems)
    try:
        areas = {
            area_id: Area(area_id, str(body["description"]), tuple(body["modules"]))
            for area_id, body in data["areas"].items()
        }
        modules = {
            rel: ModuleInfo(
                path=rel,
                areas=tuple(body["areas"]),
                imports=tuple(body["imports"]),
                markers=tuple(body["markers"]),
                summary=str(body["summary"]),
                default_arm=bool(body["default_arm"]),
            )
            for rel, body in data["modules"].items()
        }
        catalogue = Catalogue(
            schema_version=data["schema_version"],
            generator_version=data["generator_version"],
            roots=tuple(data["roots"]),
            areas=areas,
            modules=modules,
            digest=str(data["digest"]),
        )
    except (KeyError, TypeError, AttributeError) as exc:
        raise CatalogueError([f"{source}: malformed catalogue ({exc!r}); {REGENERATE_HINT}"]) from exc
    if catalogue.digest != _digest_of(catalogue):
        raise CatalogueError([f"{source}: digest mismatch: edited by hand? {REGENERATE_HINT}"])
    for rel, info in modules.items():
        for area_id in info.areas:
            if area_id not in areas or rel not in areas[area_id].modules:
                problems.append(f"{source}: {rel} names area {area_id!r} that does not list it")
    for area_id, area in areas.items():
        if not area.modules:
            problems.append(f"{source}: area {area_id!r} has no modules")
        for rel in area.modules:
            if rel not in modules or area_id not in modules[rel].areas:
                problems.append(f"{source}: area {area_id!r} lists {rel} that does not name it")
    if problems:
        raise CatalogueError(problems)
    return catalogue


def validate_catalogue(rootdir: Path, catalogue: Catalogue) -> list[str]:
    """Problems with *catalogue* against the tree at *rootdir*; ``[]`` when current.

    Current means: every catalogued module exists, every runnable module is
    catalogued, and regenerating from ``selection_areas.yaml`` reproduces it
    byte for byte.
    """
    rootdir = rootdir.resolve()
    problems: list[str] = []
    _, roots = pytest_rootdir(rootdir)
    runnable = set(relative_modules(rootdir, roots))
    for rel in sorted(catalogue.universe - runnable):
        problems.append(f"{rel}: catalogued but not a runnable module; {REGENERATE_HINT}")
    for rel in sorted(runnable - catalogue.universe):
        problems.append(f"{rel}: runnable but not catalogued; {REGENERATE_HINT}")
    try:
        rebuilt = build_catalogue(rootdir, load_areas(rootdir / AREAS_PATH))
    except CatalogueError as exc:
        return problems + exc.problems
    if render_catalogue(rebuilt) != render_catalogue(catalogue):
        problems.append(f"{CATALOGUE_PATH}: drifted from regeneration; {REGENERATE_HINT}")
    return problems


# --------------------------------------------------------------------------
# Rules


@dataclass(frozen=True)
class ScopedConftest:
    path: str
    subtree: str


@dataclass(frozen=True)
class OwnershipRule:
    paths: tuple[str, ...]
    areas: tuple[str, ...]


@dataclass(frozen=True)
class SourceScanRule:
    modules: tuple[str, ...]
    triggers: tuple[str, ...]


@dataclass(frozen=True)
class Rules:
    version: int
    global_invalidators: tuple[str, ...]
    scoped_conftests: tuple[ScopedConftest, ...]
    non_behavioral: tuple[str, ...]
    ownership: tuple[OwnershipRule, ...]
    source_scanning: tuple[SourceScanRule, ...]
    critical: tuple[str, ...]
    digest: str


def _under(subtree: str, path: str) -> bool:
    return path.startswith(subtree.rstrip("/") + "/")


def load_rules(path: Path, catalogue: Catalogue) -> Rules:
    """Parse the rules; every module and area they name must exist in *catalogue*."""
    data = _load_yaml(path)
    if not isinstance(data, dict):
        raise CatalogueError([f"{path}: expected a mapping"])
    problems: list[str] = []
    keys = {
        "version",
        "global_invalidators",
        "scoped_conftests",
        "non_behavioral",
        "ownership",
        "source_scanning",
        "critical",
    }
    _check_keys(data, keys, str(path), problems)
    if data.get("version") != RULES_VERSION:
        problems.append(f"{path}: version must be {RULES_VERSION}")

    def known_module(rel: str, where: str) -> None:
        if rel not in catalogue.modules:
            problems.append(f"{where}: {rel} is not a catalogued module")

    def known_area(area_id: str, where: str) -> None:
        if area_id not in catalogue.areas:
            problems.append(f"{where}: area {area_id!r} is not in the catalogue")

    invalidators = _str_list(
        data.get("global_invalidators"), f"{path}: global_invalidators", problems
    )
    non_behavioral = _str_list(
        data.get("non_behavioral", []), f"{path}: non_behavioral", problems, allow_empty=True
    )

    scoped: list[ScopedConftest] = []
    for index, entry in enumerate(data.get("scoped_conftests") or []):
        where = f"{path}: scoped_conftests[{index}]"
        if not isinstance(entry, dict) or not all(
            isinstance(entry.get(k), str) and entry.get(k) for k in ("path", "subtree")
        ):
            problems.append(f"{where}: needs string `path` and `subtree`")
            continue
        _check_keys(entry, {"path", "subtree"}, where, problems)
        conftest, subtree = entry["path"], entry["subtree"].rstrip("/")
        if not _under(subtree, conftest):
            problems.append(f"{where}: {conftest} is not under {subtree}")
        if not any(_under(subtree, rel) for rel in catalogue.modules):
            problems.append(f"{where}: subtree {subtree} holds no catalogued module")
        scoped.append(ScopedConftest(conftest, subtree))

    ownership: list[OwnershipRule] = []
    for index, entry in enumerate(data.get("ownership") or []):
        where = f"{path}: ownership[{index}]"
        if not isinstance(entry, dict):
            problems.append(f"{where}: must be a mapping")
            continue
        _check_keys(entry, {"paths", "areas"}, where, problems)
        paths = _str_list(entry.get("paths"), f"{where}: paths", problems)
        areas = _str_list(entry.get("areas"), f"{where}: areas", problems)
        for area_id in areas:
            known_area(area_id, where)
        ownership.append(OwnershipRule(paths, areas))

    scanning: list[SourceScanRule] = []
    for index, entry in enumerate(data.get("source_scanning") or []):
        where = f"{path}: source_scanning[{index}]"
        if not isinstance(entry, dict):
            problems.append(f"{where}: must be a mapping")
            continue
        _check_keys(entry, {"modules", "triggers"}, where, problems)
        modules = _str_list(entry.get("modules"), f"{where}: modules", problems)
        triggers = _str_list(entry.get("triggers"), f"{where}: triggers", problems)
        for rel in modules:
            known_module(rel, where)
        scanning.append(SourceScanRule(modules, triggers))

    critical = _str_list(data.get("critical"), f"{path}: critical", problems)
    for rel in critical:
        known_module(rel, f"{path}: critical")

    if problems:
        raise CatalogueError(problems)
    return Rules(
        version=RULES_VERSION,
        global_invalidators=invalidators,
        scoped_conftests=tuple(scoped),
        non_behavioral=non_behavioral,
        ownership=tuple(ownership),
        source_scanning=tuple(scanning),
        critical=critical,
        digest=file_digest(path),
    )


def _is_mapped(path: str, rules: Rules, catalogue: Catalogue, imported: frozenset[str]) -> bool:
    """Would a change to *path* be mapped by the rules rather than force a full run?

    The order and the answers mirror the mandatory-set algorithm: a global
    invalidator, a catalogued module, a scoped conftest, a non-behavioural
    path, an ownership rule, a source-scanning trigger, or a ``src`` file some
    catalogued module imports directly.
    """
    if _any_match(rules.global_invalidators, path) or path in catalogue.modules:
        return True
    if any(sc.path == path for sc in rules.scoped_conftests):
        return True
    if _any_match(rules.non_behavioral, path):
        return True
    if any(_any_match(rule.paths, path) for rule in rules.ownership):
        return True
    if any(_any_match(rule.triggers, path) for rule in rules.source_scanning):
        return True
    dotted = dotted_name(path) if path.startswith("src/") else None
    return dotted is not None and dotted in imported


def validate_rules_cover_tree(
    rootdir: Path, rules: Rules, catalogue: Catalogue, tracked: Sequence[str]
) -> list[str]:
    """Problems with *rules* against the tracked tree; ``[]`` when the rules cover it.

    *tracked* is the repository's file list (``git ls-files``), supplied by
    the caller so this module stays subprocess-free.  Reported:

    * a tracked path no rule maps (a change to it would force the full suite);
    * a path both ``non_behavioral`` and owned or scanned: non-behavioural
      wins, so the owning rule would silently never fire;
    * a rule path or glob that matches no tracked file (stale after a move);
    * a scoped conftest that does not exist under *rootdir*.
    """
    problems: list[str] = []
    tracked = sorted(set(tracked))
    imported = frozenset(name for info in catalogue.modules.values() for name in info.imports)
    for path in tracked:
        if not _is_mapped(path, rules, catalogue, imported):
            problems.append(f"{path}: no rule in {RULES_PATH} maps it")
        if _any_match(rules.non_behavioral, path):
            shadowed = [
                pattern
                for rule in rules.ownership
                for pattern in rule.paths
                if match_glob(pattern, path)
            ] + [
                pattern
                for rule in rules.source_scanning
                for pattern in rule.triggers
                if match_glob(pattern, path)
            ]
            if shadowed:
                problems.append(
                    f"{path}: non_behavioral shadows {', '.join(sorted(set(shadowed)))}"
                )
    patterns: list[tuple[str, str]] = [
        ("global_invalidators", p) for p in rules.global_invalidators
    ]
    patterns += [("non_behavioral", p) for p in rules.non_behavioral]
    patterns += [("ownership", p) for rule in rules.ownership for p in rule.paths]
    patterns += [("source_scanning", p) for rule in rules.source_scanning for p in rule.triggers]
    for section, pattern in patterns:
        if not any(match_glob(pattern, path) for path in tracked):
            kind = "glob" if _is_glob(pattern) else "path"
            problems.append(f"{section}: {kind} {pattern!r} matches no tracked file")
    for scoped in rules.scoped_conftests:
        if not (rootdir / scoped.path).is_file():
            problems.append(f"scoped_conftests: {scoped.path} does not exist")
    return problems


# --------------------------------------------------------------------------
# Policy


@dataclass(frozen=True)
class Policy:
    version: int
    question_schema_version: int
    model: str
    omit_choice: str
    omit_min_probability: float
    omit_min_confidence: float
    digest: str


def _unit_float(value: Any, where: str, problems: list[str]) -> float:
    if isinstance(value, bool) or not isinstance(value, int | float):
        problems.append(f"{where}: must be a number")
        return math.nan
    value = float(value)
    if not math.isfinite(value) or not 0.0 <= value <= 1.0:
        problems.append(f"{where}: must be within [0, 1]")
    return value


def load_policy(path: Path) -> Policy:
    data = _load_yaml(path)
    if not isinstance(data, dict):
        raise CatalogueError([f"{path}: expected a mapping"])
    problems: list[str] = []
    _check_keys(
        data, {"version", "question_schema_version", "model", "omission"}, str(path), problems
    )
    if data.get("version") != POLICY_VERSION:
        problems.append(f"{path}: version must be {POLICY_VERSION}")
    schema = data.get("question_schema_version")
    if isinstance(schema, bool) or not isinstance(schema, int) or schema < 1:
        problems.append(f"{path}: question_schema_version must be a positive integer")
    model = data.get("model")
    if not isinstance(model, str) or not model.strip():
        problems.append(f"{path}: model must be a non-empty string")
    omission = data.get("omission")
    if not isinstance(omission, dict):
        raise CatalogueError([*problems, f"{path}: `omission` must be a mapping"])
    _check_keys(
        omission, {"choice", "min_probability", "min_confidence"}, f"{path}: omission", problems
    )
    choice = omission.get("choice")
    # Only a confident "unaffected" may ever omit a module (spec §4.3).
    if choice != "unaffected":
        problems.append(f"{path}: omission.choice must be 'unaffected', not {choice!r}")
    probability = _unit_float(
        omission.get("min_probability"), f"{path}: omission.min_probability", problems
    )
    confidence = _unit_float(
        omission.get("min_confidence"), f"{path}: omission.min_confidence", problems
    )
    if problems:
        raise CatalogueError(problems)
    return Policy(
        version=POLICY_VERSION,
        question_schema_version=schema,
        model=model.strip(),
        omit_choice=choice,
        omit_min_probability=probability,
        omit_min_confidence=confidence,
        digest=file_digest(path),
    )
