"""A small git project shaped like this one, for the test-selection tests.

Tasks 2-4, 9 and 13 of the smart-test-selection plan share it: the change
snapshot, the mandatory set, the static-impact adapter, the selection service
and the replay harness all run against the same committed tree and its
reviewed ``tests/selection_*`` artifacts, so a fact one of them relies on (an
area, an ownership rule, a function-local import) is written down once.

The layout, every file committed in the base commit on ``main``:

.. code-block:: text

    pyproject.toml            [tool.pytest.ini_options] testpaths = ["tests"]
    src/pkg/__init__.py       (empty)
    src/pkg/a.py              def alpha(): return 1
    src/pkg/b.py              def beta(): from .a import alpha; return alpha() + 1  (function-local import)
    src/pkg/c.py              def gamma(): return 3
    src/pkg/data.json         {"k": 1}
    docs/README.md            "# docs"
    tests/conftest.py         (empty)
    tests/test_a.py           imports src.pkg.a
    tests/sub/__init__.py, tests/sub/conftest.py (a fixture), tests/sub/test_b.py (imports src.pkg.b)
    tests/test_c.py           imports src.pkg.c
    tests/test_docs_scan.py   reads docs/README.md
    tests/selection_areas.yaml, tests/selection_rules.yaml, tests/selection_policy.yaml
    tests/selection_catalogue.json  (generated by src.test_selection.catalogue)

``origin`` is a bare clone beside the repository (``<root>.origin.git``), so
``origin/main`` resolves and the working tree is clean.
"""

from __future__ import annotations

import importlib.util
import subprocess
from pathlib import Path

FILES: dict[str, str] = {
    "pyproject.toml": '[tool.pytest.ini_options]\ntestpaths = ["tests"]\n',
    "src/pkg/__init__.py": "",
    "src/pkg/a.py": "def alpha():\n    return 1\n",
    "src/pkg/b.py": "def beta():\n    from .a import alpha\n\n    return alpha() + 1\n",
    "src/pkg/c.py": "def gamma():\n    return 3\n",
    "src/pkg/data.json": '{"k": 1}\n',
    "docs/README.md": "# docs\n",
    "tests/conftest.py": "",
    "tests/test_a.py": (
        "from src.pkg.a import alpha\n\n\ndef test_alpha():\n    assert alpha() == 1\n"
    ),
    "tests/sub/__init__.py": "",
    "tests/sub/conftest.py": (
        "import pytest\n\n\n@pytest.fixture\ndef beta_expected():\n    return 2\n"
    ),
    "tests/sub/test_b.py": (
        "from src.pkg.b import beta\n\n\n"
        "def test_beta(beta_expected):\n    assert beta() == beta_expected\n"
    ),
    "tests/test_c.py": (
        "from src.pkg.c import gamma\n\n\ndef test_gamma():\n    assert gamma() == 3\n"
    ),
    "tests/test_docs_scan.py": (
        "from pathlib import Path\n\n"
        "ROOT = Path(__file__).resolve().parent.parent\n\n\n"
        "def test_docs_readme_has_a_title():\n"
        '    assert (ROOT / "docs" / "README.md").read_text().startswith("# ")\n'
    ),
    "tests/selection_areas.yaml": """\
version: 1
areas:
  - id: alpha
    description: "The alpha function returns one."
    match: ["tests/test_a.py"]
  - id: beta
    description: "The beta function adds one to alpha, using the sub-package fixture."
    match: ["tests/sub/*.py"]
  - id: gamma
    description: "The gamma function returns three."
    match: ["tests/test_c.py"]
  - id: docs-guards
    description: "The documentation README keeps a title line."
    match: ["tests/test_docs_scan.py"]
""",
    "tests/selection_rules.yaml": """\
version: 1
global_invalidators:
  - "pyproject.toml"
  - "tests/conftest.py"
scoped_conftests:
  - { path: "tests/sub/conftest.py", subtree: "tests/sub" }
non_behavioral:
  - "*.md"
ownership:
  - { paths: ["src/pkg/a.py"], areas: ["alpha"] }
  - { paths: ["src/pkg/b.py"], areas: ["beta"] }
  - { paths: ["src/pkg/c.py"], areas: ["gamma"] }
  - { paths: ["docs/**"], areas: ["docs-guards"] }
source_scanning:
  - { modules: ["tests/test_docs_scan.py"], triggers: ["docs/**"] }
critical:
  - "tests/test_a.py"
""",
    "tests/selection_policy.yaml": """\
version: 1
question_schema_version: 1
model: "jev-1.13.0"
omission:
  choice: unaffected
  min_probability: 0.98
  min_confidence: 0.90
""",
}


def git(repo: Path, *args: str) -> str:
    """Run git in *repo* and return its stdout; a nonzero status raises."""
    return subprocess.run(
        ["git", *args], cwd=repo, check=True, capture_output=True, text=True
    ).stdout


def build_fixture_repo(root: Path) -> Path:
    """Create the fixture project at *root*, commit it on ``main`` and give it an ``origin``.

    Returns *root*. ``origin/main`` resolves to the single base commit and the
    working tree is clean.
    """
    root.mkdir(parents=True)
    git(root, "init", "-q", "-b", "main")
    # Repository-local identity: a CI runner has no global one, and a box's
    # global signing or hook settings must not reach the fixture's commits.
    git(root, "config", "user.name", "Selection Fixture")
    git(root, "config", "user.email", "fixture@example.invalid")
    git(root, "config", "commit.gpgsign", "false")
    git(root, "config", "core.hooksPath", "/dev/null")
    # Anything that imports the fixture's modules must not dirty its tree.
    (root / ".git" / "info" / "exclude").write_text("__pycache__/\n*.pyc\n")
    for relative, text in FILES.items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    _write_catalogue(root)
    git(root, "add", "-A")
    git(root, "commit", "-q", "-m", "fixture base")
    origin = root.with_name(root.name + ".origin.git")
    git(root.parent, "clone", "-q", "--bare", str(root), str(origin))
    git(root, "remote", "add", "origin", str(origin))
    git(root, "fetch", "-q", "origin")
    return root


def _write_catalogue(root: Path) -> None:
    """Write ``tests/selection_catalogue.json`` with the catalogue generator.

    The generator (``src.test_selection.catalogue``) and this fixture were
    written by sibling tasks of the same plan that start together, so until
    both have landed the fixture is built without the catalogue; nothing the
    change snapshot checks reads it. Once the module exists it is always used.
    """
    if importlib.util.find_spec("src.test_selection.catalogue") is None:
        return
    from src.test_selection import catalogue

    areas = catalogue.load_areas(root / catalogue.AREAS_PATH)
    built = catalogue.build_catalogue(root, areas)
    (root / catalogue.CATALOGUE_PATH).write_text(catalogue.render_catalogue(built))
