"""Behavioral tests for the setup wizard (platform plan 8-12).

Exercises the wizard's filesystem, config-merge, database-selection, and
final-write behavior under a temporary ``HOME`` — the surfaces that create
unusable or secret-leaking installations when they regress.  Interactive
prompts and network/subprocess probes are patched at the module boundary;
all file effects are real.
"""

from __future__ import annotations

import os
from pathlib import Path

import pytest

import src.setup_wizard as sw


@pytest.fixture
def fake_home(tmp_path, monkeypatch) -> Path:
    """Point ``~`` at an isolated temp directory for the duration of a test."""
    monkeypatch.setenv("HOME", str(tmp_path))
    return tmp_path


def test_load_existing_config_merges_yaml_and_env_without_resolving_secrets(fake_home):
    config_dir = fake_home / ".agent-queue"
    config_dir.mkdir()
    (config_dir / ".env").write_text(
        "# secrets live here\n"
        "DISCORD_BOT_TOKEN=secret-token\n"
        "THIS LINE HAS NO ASSIGNMENT\n"
        "ANTHROPIC_API_KEY = spaced-value\n"
        "\n",
        encoding="utf-8",
    )
    (config_dir / "config.yaml").write_text(
        "# generated by setup wizard\n"
        "workspace_dir: /srv/workspaces\n"
        "database_path: /srv/aq.db\n"
        "discord:\n"
        "  bot_token: ${DISCORD_BOT_TOKEN}\n"
        '  guild_id: "42"\n',
        encoding="utf-8",
    )

    existing = sw._load_existing_config()

    # Env-derived values, whitespace-normalized; malformed lines ignored.
    assert existing["DISCORD_BOT_TOKEN"] == "secret-token"
    assert existing["ANTHROPIC_API_KEY"] == "spaced-value"
    assert "THIS LINE HAS NO ASSIGNMENT" not in existing

    # Raw YAML is returned verbatim: the ${...} secret reference is NOT
    # resolved against the .env value.
    yaml_cfg = existing["_yaml"]
    assert yaml_cfg["workspace_dir"] == "/srv/workspaces"
    assert yaml_cfg["database_path"] == "/srv/aq.db"
    assert yaml_cfg["discord"]["bot_token"] == "${DISCORD_BOT_TOKEN}"
    assert yaml_cfg["discord"]["guild_id"] == "42"


def test_step_database_keeps_existing_sqlite_and_creates_parent(fake_home, monkeypatch):
    db_path = str(fake_home / "aq-data" / "agent-queue.db")
    monkeypatch.setattr(sw, "prompt_yes_no", lambda *a, **kw: False)  # don't switch

    result = sw.step_database({"DATABASE_PATH": db_path})

    assert result == {"backend": "sqlite", "url": db_path}
    assert os.path.isdir(os.path.dirname(db_path))


def test_select_postgresql_stops_after_two_failed_dsn_attempts(monkeypatch):
    attempted: list[str] = []
    prompts = iter(["postgresql://first@localhost/aq", "postgresql://second@localhost/aq"])

    monkeypatch.setattr(sw, "_ensure_asyncpg", lambda: True)
    monkeypatch.setattr(sw, "_check_pg_running", lambda *a, **kw: True)
    monkeypatch.setattr(sw, "prompt_yes_no", lambda *a, **kw: True)  # use local PG
    monkeypatch.setattr(sw, "prompt", lambda *a, **kw: next(prompts))

    def failing_dsn_test(dsn):
        attempted.append(dsn)
        return False

    monkeypatch.setattr(sw, "_test_pg_dsn", failing_dsn_test)

    with pytest.raises(SystemExit) as excinfo:
        sw._select_postgresql()

    assert excinfo.value.code == 1
    # Both prompted DSNs were tried; no config was emitted after the second
    # failure (SystemExit propagated instead of a return value).
    assert attempted == [
        "postgresql://first@localhost/aq",
        "postgresql://second@localhost/aq",
    ]


def test_build_pg_config_offers_existing_sqlite_migration(tmp_path, monkeypatch):
    sqlite_path = tmp_path / "legacy.db"
    sqlite_path.write_bytes(b"sqlite payload")
    monkeypatch.setattr(sw, "prompt_yes_no", lambda *a, **kw: True)  # migrate

    dsn = "postgresql://agent_queue:pw@localhost:5533/agent_queue"
    config = sw._build_pg_config(dsn, str(sqlite_path))

    assert config == {
        "backend": "postgresql",
        "url": dsn,
        "pool_min_size": 2,
        "pool_max_size": 10,
        "_migrate_from": str(sqlite_path),
    }


def test_step_write_config_persists_env_references_and_migration_without_plaintext_secret(
    fake_home, monkeypatch
):
    monkeypatch.setattr(sw, "_offer_shell_env", lambda env_path: None)

    db_config = {
        "backend": "postgresql",
        "url": "postgresql://agent_queue:pw@localhost:5533/agent_queue",
        "pool_min_size": 2,
        "pool_max_size": 10,
        "_migrate_from": str(fake_home / "legacy.db"),
    }
    discord_cfg = {
        "bot_token": "discord-secret-token",
        "guild_id": "424242",
        "channels": {
            "control": "control",
            "notifications": "notifications",
            "agent_questions": "agent-questions",
        },
        "authorized_users": [],
        "per_project_channels": {},
    }
    agents_cfg = {"claude": {"from_env": False, "api_key": "sk-test-secret"}}
    sched_cfg = {
        "scheduling": {"rolling_window_hours": 24},
        "pause_retry": {
            "rate_limit_backoff_seconds": 60,
            "token_exhaustion_retry_seconds": 120,
        },
    }

    config_path = sw.step_write_config(
        str(fake_home / "workspaces"), db_config, discord_cfg, agents_cfg, sched_cfg
    )

    yaml_text = config_path.read_text(encoding="utf-8")
    env_path = fake_home / ".agent-queue" / ".env"
    env_text = env_path.read_text(encoding="utf-8")

    # YAML references secrets via ${...}; the values live only in .env.
    assert "bot_token: ${DISCORD_BOT_TOKEN}" in yaml_text
    assert "discord-secret-token" not in yaml_text
    assert "sk-test-secret" not in yaml_text
    assert "DISCORD_BOT_TOKEN=discord-secret-token" in env_text
    assert "ANTHROPIC_API_KEY=sk-test-secret" in env_text

    # .env is restrictive: owner read/write only.
    assert (env_path.stat().st_mode & 0o777) == 0o600

    # The migration marker is an in-memory handoff to the migration step —
    # it must never be serialized into the config document.
    assert "_migrate_from" not in yaml_text
    assert f"url: {db_config['url']}" in yaml_text
