// Generated by tools/capture — do not edit.
// Regenerate with `pnpm --filter @aqw/capture capture`.

export interface CaptureSource {
  format: 'avif' | 'webp';
  src: string;
  width: number;
  height: number;
  bytes: number;
}

export interface CaptureImage {
  surface: string;
  title: string;
  viewport: string;
  theme: 'dark' | 'light';
  route: string;
  /** CSS pixels — the intrinsic size to render at, not the file's pixel size. */
  width: number;
  height: number;
  sources: CaptureSource[];
  /** Inline blurred data URI, safe to use as a background while loading. */
  placeholder: string;
}

export interface CaptureReelFrame {
  index: number;
  beat: string;
  label: string;
  sources: CaptureSource[];
}

export interface CaptureReel {
  id: string;
  fps: number;
  width: number;
  height: number;
  beats: { id: string; label: string }[];
  frameCount: number;
  frames: CaptureReelFrame[];
  video: { format: 'webm'; src: string; bytes: number } | null;
  placeholder: string;
}

export interface CaptureSources {
  repository: { path: string; name?: string; revision: string; [key: string]: unknown };
  outrider: { path: string; revision: string; binary?: string };
  queries: Record<string, string | number>;
  tour: {
    view: string;
    title: string | null;
    author: string | null;
    step: number;
    stepCount: number;
    target: string;
    status?: unknown;
  } | null;
  commentPrompt: { command: string; text: string; file?: string } | null;
  states: Record<string, { state: string; commands: string[]; rendered: boolean }>;
  reels: Record<string, Record<string, unknown> | null>;
  commands: string[];
}

export interface CaptureManifest {
  version: number;
  /** A deterministic demo seed when the capture has one. */
  seed: number | null;
  epoch: string | null;
  recordedAt: string | null;
  project: { id: string; name: string };
  /**
   * Provenance for captures without a seeded world (the native Outrider
   * runner): corpus and app revisions, the queries typed, the tour played and
   * the CLI commands behind each state. Null for the browser pipeline.
   */
  sources: CaptureSources | null;
  surfaces: string[];
  themes: string[];
  viewports: string[];
  images: Record<string, CaptureImage>;
  reels: Record<string, CaptureReel>;
}

declare const manifest: CaptureManifest;
export default manifest;
