#!/usr/bin/env bash
# One entry point for deploying Agent Queue, locally or to GCP.
#
# Everything is driven by variables with defaults, so a fresh clone can get to a
# running stack without editing files in the repository. Run `deploy.sh help`
# for the full list.
#
#   ./deploy.sh preflight          # is this machine ready?
#   ./deploy.sh local up           # whole stack on this box, incl. PostgreSQL
#   ./deploy.sh gcp apply          # one VM + Cloud SQL, per terraform/gcp/
#   ./deploy.sh login              # authenticate the harnesses (human-only)
#
# Design rules, because this is an open-source project and repeatability is the
# point:
#   * No step depends on the caller's working directory.
#   * Every failure explains the fix rather than just the symptom.
#   * Re-running any command is safe.
#   * Nothing here holds a secret; secrets live in .env or Secret Manager.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

# --- configuration (override by exporting, or via a .env) --------------------

AQ_COMPOSE_FILE="${AQ_COMPOSE_FILE:-${SCRIPT_DIR}/docker-compose.prod.yml}"
AQ_ENV_FILE="${AQ_ENV_FILE:-${SCRIPT_DIR}/.env}"
AQ_TF_DIR="${AQ_TF_DIR:-${SCRIPT_DIR}/terraform/gcp}"
AQ_DASHBOARD_PORT="${AQ_DASHBOARD_PORT:-8088}"
AQ_HARNESSES="${AQ_HARNESSES:-claude,codex}"
# Local runs bring their own PostgreSQL; a cloud run points at a managed one.
AQ_LOCAL_DSN="${AQ_LOCAL_DSN:-postgresql+asyncpg://agent_queue:agent_queue_dev@postgres:5432/agent_queue}"

RED=$'\033[31m'; YEL=$'\033[33m'; GRN=$'\033[32m'; DIM=$'\033[2m'; OFF=$'\033[0m'
[[ -t 1 ]] || { RED=""; YEL=""; GRN=""; DIM=""; OFF=""; }

die()  { printf '%serror:%s %s\n' "$RED" "$OFF" "$*" >&2; exit 1; }
warn() { printf '%swarn:%s %s\n'  "$YEL" "$OFF" "$*" >&2; }
ok()   { printf '%s  ok%s  %s\n'  "$GRN" "$OFF" "$*"; }
step() { printf '\n%s==>%s %s\n' "$GRN" "$OFF" "$*"; }

have() { command -v "$1" >/dev/null 2>&1; }

compose() {
  docker compose -f "$AQ_COMPOSE_FILE" "$@"
}

# --- preflight ---------------------------------------------------------------

require_docker() {
  have docker || die "docker is not installed. See https://docs.docker.com/engine/install/"
  docker compose version >/dev/null 2>&1 \
    || die "the docker compose v2 plugin is missing (\`docker compose version\` failed).
       Install docker-compose-plugin, not the legacy docker-compose binary."
  docker info >/dev/null 2>&1 \
    || die "cannot talk to the Docker daemon. Is it running, and is your user in the docker group?"
}

cmd_preflight() {
  local failed=0
  step "Tooling"
  for tool in docker git; do
    if have "$tool"; then ok "$tool"; else printf '%s  --%s  %s (missing)\n' "$RED" "$OFF" "$tool"; failed=1; fi
  done
  if docker compose version >/dev/null 2>&1; then ok "docker compose v2"; else
    printf '%s  --%s  docker compose v2 (missing)\n' "$RED" "$OFF"; failed=1
  fi
  for tool in terraform gcloud; do
    if have "$tool"; then ok "$tool $(dim_version "$tool")"; else
      printf '%s  --%s  %s (only needed for `deploy.sh gcp`)\n' "$YEL" "$OFF" "$tool"
    fi
  done

  step "Ports"
  if port_busy "$AQ_DASHBOARD_PORT"; then
    warn "port ${AQ_DASHBOARD_PORT} is in use — set AQ_DASHBOARD_PORT to something free"
  else
    ok "dashboard port ${AQ_DASHBOARD_PORT} is free"
  fi

  step "Configuration"
  if [[ -f "$AQ_ENV_FILE" ]]; then ok "$(basename "$AQ_ENV_FILE") exists"; else
    warn "no $(basename "$AQ_ENV_FILE") yet — \`deploy.sh local up\` will create one"
  fi

  (( failed == 0 )) || die "preflight failed; install what is marked missing above."
  printf '\n%sready%s\n' "$GRN" "$OFF"
}

dim_version() { printf '%s%s%s' "$DIM" "$("$1" version 2>/dev/null | head -1)" "$OFF"; }

port_busy() {
  local p="$1"
  if have ss; then ss -ltn 2>/dev/null | grep -q ":${p} "
  elif have lsof; then lsof -iTCP:"${p}" -sTCP:LISTEN >/dev/null 2>&1
  else return 1
  fi
}

# --- local -------------------------------------------------------------------

ensure_env_file() {
  [[ -f "$AQ_ENV_FILE" ]] && return 0
  step "Creating $(basename "$AQ_ENV_FILE")"
  umask 077
  cat > "$AQ_ENV_FILE" <<EOF
# Generated by deploy.sh. Safe to edit; gitignored.
AQ_DATABASE_URL=${AQ_LOCAL_DSN}
AQ_HARNESSES=${AQ_HARNESSES}
AQ_DASHBOARD_PORT=${AQ_DASHBOARD_PORT}
EOF
  umask 022
  ok "wrote $AQ_ENV_FILE (local PostgreSQL; edit AQ_DATABASE_URL to point elsewhere)"
}

cmd_local() {
  require_docker
  case "${1:-up}" in
    up)
      ensure_env_file
      step "Building and starting the stack"
      compose --profile local-db up -d --build
      wait_for_health
      printf '\nDashboard: %shttp://127.0.0.1:%s%s\n' "$GRN" "$AQ_DASHBOARD_PORT" "$OFF"
      printf 'Next: %s./deploy.sh login%s to authenticate the harnesses.\n' "$DIM" "$OFF"
      ;;
    down)   step "Stopping"; compose --profile local-db down ;;
    # `down -v` would delete the volumes holding the vault, every worktree slot
    # and the harness logins, so it is spelled out rather than offered as a flag.
    destroy)
      printf 'This deletes the vault, all worktree slots and the harness logins.\n'
      read -r -p 'Type the word DESTROY to continue: ' reply
      [[ "$reply" == "DESTROY" ]] || die "aborted"
      compose --profile local-db down -v
      ;;
    logs)   compose logs -f --tail=200 "${2:-daemon}" ;;
    status) compose --profile local-db ps ;;
    shell)  compose exec "${2:-daemon}" bash ;;
    health) curl -fsS "http://127.0.0.1:${AQ_DASHBOARD_PORT}/health" | python3 -m json.tool ;;
    *) die "unknown: local ${1}. Try: up, down, destroy, logs, status, shell, health" ;;
  esac
}

wait_for_health() {
  step "Waiting for the daemon"
  local url="http://127.0.0.1:${AQ_DASHBOARD_PORT}/health" i=0
  until curl -fsS -o /dev/null "$url" 2>/dev/null; do
    i=$((i + 1))
    (( i > 60 )) && { warn "not healthy after ~3min; try: ./deploy.sh local logs"; return 0; }
    sleep 3
  done
  ok "healthy"
}

# --- harness login -----------------------------------------------------------

cmd_login() {
  require_docker
  # AQ never types a credential, so these are interactive by design. Each
  # persists on its own volume and survives `up --build`.
  local which="${1:-all}"
  case "$which" in
    claude|all)
      step "Claude"
      compose exec daemon claude auth login || warn "claude login did not complete"
      ;;&
    codex|all)
      step "Codex"
      compose exec daemon codex login --device-auth || warn "codex login did not complete"
      ;;
    *) die "unknown: login ${which}. Try: claude, codex, all" ;;
  esac
  printf '\n%sVerify:%s ./deploy.sh local shell  then  claude auth status\n' "$DIM" "$OFF"
}

# --- gcp ---------------------------------------------------------------------

require_tf() {
  have terraform || die "terraform is not installed. See https://developer.hashicorp.com/terraform/install"
  [[ -d "$AQ_TF_DIR" ]] || die "no terraform directory at $AQ_TF_DIR"
  if [[ ! -f "${AQ_TF_DIR}/terraform.tfvars" ]]; then
    die "no terraform.tfvars in ${AQ_TF_DIR}.
       cp ${AQ_TF_DIR}/terraform.tfvars.example ${AQ_TF_DIR}/terraform.tfvars
       then set project_id (the only required value)."
  fi
}

require_gcloud() {
  have gcloud || die "gcloud is not installed. See https://cloud.google.com/sdk/docs/install"
  gcloud auth list --filter=status:ACTIVE --format='value(account)' 2>/dev/null | grep -q . \
    || die "not authenticated. Run: gcloud auth login && gcloud auth application-default login"
}

tf() { terraform -chdir="$AQ_TF_DIR" "$@"; }

# Read a value from terraform.tfvars, falling back to the variable's default so
# `stop` works even when the caller never overrode zone/name.
tf_var() {
  local key="$1" val
  val="$(sed -nE "s/^[[:space:]]*${key}[[:space:]]*=[[:space:]]*\"([^\"]*)\".*/\\1/p" \
        "${AQ_TF_DIR}/terraform.tfvars" 2>/dev/null | head -1)"
  if [[ -z "$val" ]]; then
    case "$key" in
      zone) val="us-central1-a" ;;
      name) val="agent-queue" ;;
      *) die "could not read ${key} from terraform.tfvars" ;;
    esac
  fi
  printf '%s' "$val"
}

cmd_gcp() {
  case "${1:-plan}" in
    init)    require_tf; tf init ;;
    plan)    require_tf; require_gcloud; tf init -input=false >/dev/null; tf plan ;;
    apply)   require_tf; require_gcloud; tf init -input=false >/dev/null; tf apply ;;
    output)  require_tf; tf output ;;
    destroy)
      require_tf; require_gcloud
      warn "the data disk has prevent_destroy set; remove it deliberately if you mean to."
      tf destroy
      ;;
    stop)
      # Stopping is safe by design: the daemon's restart recovery resets BUSY
      # agents, releases every workspace lock as stale, and returns IN_PROGRESS
      # tasks to READY. Compute stops billing; disks do not.
      require_tf; require_gcloud
      step "Stopping the VM (disks keep billing)"
      gcloud compute instances stop "$(tf output -raw vm_name)" \
        --zone "$(tf_var zone)" --project "$(tf_var project_id)"
      printf '\n%sAlso stop the database to reach the real floor:%s\n  ./deploy.sh gcp db-stop\n' "$DIM" "$OFF"
      ;;
    start)
      require_tf; require_gcloud
      step "Starting the VM"
      gcloud compute instances start "$(tf output -raw vm_name)" \
        --zone "$(tf_var zone)" --project "$(tf_var project_id)"
      printf '\ncloud-init re-runs on boot and brings the stack back up.\n'
      ;;
    db-stop)
      require_tf; require_gcloud
      step "Stopping Cloud SQL (storage still bills)"
      gcloud sql instances patch "$(tf_var name)-pg" --activation-policy NEVER \
        --project "$(tf_var project_id)" --quiet
      ;;
    db-start)
      require_tf; require_gcloud
      step "Starting Cloud SQL"
      gcloud sql instances patch "$(tf_var name)-pg" --activation-policy ALWAYS \
        --project "$(tf_var project_id)" --quiet
      ;;
    ssh)     require_tf; require_gcloud; eval "$(tf output -raw ssh_command)" ;;
    tunnel)
      require_tf; require_gcloud
      printf 'Then open %shttp://127.0.0.1:%s%s\n\n' "$GRN" "$AQ_DASHBOARD_PORT" "$OFF"
      eval "$(tf output -raw dashboard_tunnel_command)"
      ;;
    *) die "unknown: gcp ${1}. Try: init, plan, apply, output, ssh, tunnel, stop, start, db-stop, db-start, destroy" ;;
  esac
}

# --- help --------------------------------------------------------------------

cmd_help() {
  cat <<EOF
Agent Queue deployment.

  ./deploy.sh preflight              check this machine has what it needs
  ./deploy.sh local up               build and start everything here
  ./deploy.sh local down|status|logs|shell|health
  ./deploy.sh local destroy          delete the volumes too (asks first)
  ./deploy.sh login [claude|codex]   authenticate a harness (interactive)
  ./deploy.sh gcp plan|apply         provision one VM + Cloud SQL
  ./deploy.sh gcp ssh|tunnel|output|destroy
  ./deploy.sh gcp stop|start         stop/start the VM (disks keep billing)
  ./deploy.sh gcp db-stop|db-start   stop/start Cloud SQL (storage keeps billing)

Variables (export to override):

  AQ_DASHBOARD_PORT   ${AQ_DASHBOARD_PORT}
                      host port for the dashboard, bound to 127.0.0.1 only
  AQ_HARNESSES        ${AQ_HARNESSES}
                      harness CLIs baked into the image at build time
  AQ_DATABASE_URL     (in ${AQ_ENV_FILE##*/})
                      one whole DSN; never split the password out
  AQ_ENV_FILE         ${AQ_ENV_FILE}
  AQ_COMPOSE_FILE     ${AQ_COMPOSE_FILE}
  AQ_TF_DIR           ${AQ_TF_DIR}
  AQ_LOCAL_DSN        DSN written into a fresh .env for local runs

Reading: deploy/README.md for how, deploy/DESIGN.md for why.
EOF
}

# --- dispatch ----------------------------------------------------------------

case "${1:-help}" in
  preflight) shift; cmd_preflight "$@" ;;
  local)     shift; cmd_local "$@" ;;
  login)     shift; cmd_login "$@" ;;
  gcp)       shift; cmd_gcp "$@" ;;
  help|-h|--help) cmd_help ;;
  *) printf 'unknown command: %s\n\n' "$1" >&2; cmd_help >&2; exit 2 ;;
esac
