"""add pane_open + body_kind to messages

Revision ID: 0c466030a9da
Revises: 90d653cbed1d
Create Date: 2026-08-22 16:36:57.943416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c466030a9da'
down_revision: Union[str, Sequence[str], None] = '90d653cbed1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_kind', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pane_open', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('pane_open')
        batch_op.drop_column('body_kind')

    # ### end Alembic commands ###
