"""dv2 phase1 control plane

Revision ID: 0ff97e8792f8
Revises: a1c7f3e08b42
Create Date: 2026-08-21 21:40:18.455091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ff97e8792f8'
down_revision: Union[str, Sequence[str], None] = 'a1c7f3e08b42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_class', sa.Text(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('needs_workspace', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    with op.batch_alter_table('archived_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dedup_key', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('intelligence_class', sa.Text(), nullable=True))

    with op.batch_alter_table('playbook_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Text(), nullable=True))
        batch_op.create_index('uq_playbook_runs_pb_event', ['playbook_id', 'event_id'], unique=True, sqlite_where=sa.text('event_id IS NOT NULL'), postgresql_where=sa.text('event_id IS NOT NULL'))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dedup_key', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('intelligence_class', sa.Text(), nullable=True))
        batch_op.create_index('idx_tasks_project_dedup', ['project_id', 'dedup_key'], unique=False)

    with op.batch_alter_table('gates', schema=None) as batch_op:
        batch_op.drop_constraint('ck_gates_type', type_='check')
        batch_op.create_check_constraint(
            'ck_gates_type',
            "gate_type IN ('human','timer','pr-merged','ci-run','event','task','routing')",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_tasks_project_dedup')
        batch_op.drop_column('intelligence_class')
        batch_op.drop_column('dedup_key')

    with op.batch_alter_table('playbook_runs', schema=None) as batch_op:
        batch_op.drop_index('uq_playbook_runs_pb_event', sqlite_where=sa.text('event_id IS NOT NULL'), postgresql_where=sa.text('event_id IS NOT NULL'))
        batch_op.drop_column('event_id')

    with op.batch_alter_table('archived_tasks', schema=None) as batch_op:
        batch_op.drop_column('intelligence_class')
        batch_op.drop_column('dedup_key')

    with op.batch_alter_table('agent_profiles', schema=None) as batch_op:
        batch_op.drop_column('needs_workspace')
        batch_op.drop_column('default_class')

    with op.batch_alter_table('gates', schema=None) as batch_op:
        batch_op.drop_constraint('ck_gates_type', type_='check')
        batch_op.create_check_constraint(
            'ck_gates_type',
            "gate_type IN ('human','timer','pr-merged','ci-run','event','task')",
        )

    # ### end Alembic commands ###
