"""profile capability namespaces

Playbook V2 Package 0 §6.  Three additive, nullable Text columns on
``agent_profiles`` holding JSON arrays, matching how ``allowed_tools`` and
``mcp_servers`` are already stored on this table.

**No data migration, and no backfill.** ``NULL`` is meaningful: it is the
signal that the legacy ``allowed_tools`` adapter should run.  Backfilling
would erase the distinction between "authored as none" (``'[]'``) and "not
authored" (``NULL``), which is the whole basis of the audit/enforce split.

Because the columns are additive and nullable, reverting Package 0's code
needs **no** database downgrade — a downgraded database still describes
every profile's rights exactly as it did before Package 0, since
``allowed_tools`` is never removed or rewritten by this package.

Portability: ``Text`` + ``nullable=True`` with no server default is
metadata-only on PostgreSQL (no table rewrite, no long lock) and a plain
``ADD COLUMN`` on SQLite.  ``batch_alter_table`` is used defensively so the
downgrade also works on SQLite older than 3.35, where ``DROP COLUMN`` is
unsupported; it costs nothing on the upgrade path.

Note: the autogenerated draft of this revision additionally proposed
recreating unrelated ``agents``/``tasks`` foreign keys under new names.
That is autogenerate noise against the pre-existing schema, not a change
this package makes, and it was removed.

Revision ID: 3b560dbd527c
Revises: d7f4c1a9b2e8
Create Date: 2026-09-01 12:17:46.475954

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3b560dbd527c"
down_revision: Union[str, Sequence[str], None] = "d7f4c1a9b2e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_COLUMNS = ("harness_tools", "aq_commands", "plugin_tools")


def upgrade() -> None:
    """Add the three capability-namespace columns."""
    with op.batch_alter_table("agent_profiles", schema=None) as batch_op:
        for name in _COLUMNS:
            batch_op.add_column(sa.Column(name, sa.Text(), nullable=True))


def downgrade() -> None:
    """Drop them.  Safe: nothing references these columns."""
    with op.batch_alter_table("agent_profiles", schema=None) as batch_op:
        for name in reversed(_COLUMNS):
            batch_op.drop_column(name)
