"""add triage deferrals

Revision ID: 4f43094cd7de
Revises: 72671cc2b86c
Create Date: 2026-08-31 15:33:49.144674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f43094cd7de'
down_revision: Union[str, Sequence[str], None] = '72671cc2b86c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_routing_deferrals',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('task_id', sa.Text(), nullable=False),
    sa.Column('routing_revision', sa.Integer(), nullable=False),
    sa.Column('playbook_run_id', sa.Text(), nullable=False),
    sa.Column('catalog_generation', sa.Text(), nullable=False),
    sa.Column('policy_generation', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('deferred_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'routing_revision', 'catalog_generation', 'policy_generation', name='uq_task_routing_deferral_generation')
    )
    with op.batch_alter_table('task_routing_deferrals', schema=None) as batch_op:
        batch_op.create_index('idx_task_routing_deferrals_project', ['project_id', 'deferred_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_routing_deferrals', schema=None) as batch_op:
        batch_op.drop_index('idx_task_routing_deferrals_project')

    op.drop_table('task_routing_deferrals')
    # ### end Alembic commands ###
