"""add task_proposals table

Revision ID: 5ba6efdd01d0
Revises: c17d35836ed3
Create Date: 2026-08-22 12:08:04.568421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ba6efdd01d0'
down_revision: Union[str, Sequence[str], None] = 'c17d35836ed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_proposals',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'ready', 'committed', 'discarded')", name='ck_task_proposals_status'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_proposals', schema=None) as batch_op:
        batch_op.create_index('idx_task_proposals_project_status', ['project_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_proposals', schema=None) as batch_op:
        batch_op.drop_index('idx_task_proposals_project_status')

    op.drop_table('task_proposals')
    # ### end Alembic commands ###
