"""add partial unique index on open gates for TOCTOU safety

Revision ID: 90d653cbed1d
Revises: 5ba6efdd01d0
Create Date: 2026-08-22 13:09:02.528535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90d653cbed1d'
down_revision: Union[str, Sequence[str], None] = '5ba6efdd01d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gates', schema=None) as batch_op:
        batch_op.create_index('uq_gates_open_dedup', ['project_id', 'gate_type', 'await_id'], unique=True, sqlite_where=sa.text("status = 'open'"), postgresql_where=sa.text("status = 'open'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gates', schema=None) as batch_op:
        batch_op.drop_index('uq_gates_open_dedup', sqlite_where=sa.text("status = 'open'"), postgresql_where=sa.text("status = 'open'"))

    # ### end Alembic commands ###
