"""playbook v2: durable run snapshots and execution receipts

Revision ID: b3f2c0de0002
Revises: e1b7c2a94d38
Create Date: 2026-09-01

Additive: two new tables.  Second in the Package 3 chain (child plan §4.3) —
playbook_v2_runs.artifact_sha256 references playbook_artifacts, created by
a3f1c0de0001, and playbook_step_receipts.run_id references this revision's
own run table, so the create/drop order is fixed both ways.

The chain still runs after a3f1c0de0001, but not *immediately* after it: by
the time this branch rebased, main's head had moved on to e1b7c2a94d38 (which
itself chains from a3f1c0de0001).  §4.3 rule 1 tells Task B to leave its
down_revision alone, but that instruction assumed a3f1c0de0001 would still be
the tip; keeping it would have split the chain into two heads and broken
§4.3 rule 2, which is the rule the ordering exists to serve.

The partial unique index on (dispatch_id, rule_id) is hand-written rather
than autogenerated: autogenerate renders partial indexes badly, and the
predicate has to be identical on both dialects.
"""

import sqlalchemy as sa
from alembic import op

revision = "b3f2c0de0002"
down_revision = "e1b7c2a94d38"
branch_labels = None
depends_on = None

_DISPATCH_WHERE = "dispatch_id IS NOT NULL"


def upgrade() -> None:
    op.create_table(
        "playbook_v2_runs",
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("playbook_id", sa.Text(), nullable=False),
        sa.Column("artifact_sha256", sa.Text(), nullable=False),
        sa.Column("rule_id", sa.Text(), nullable=False),
        sa.Column("lifecycle", sa.Text(), server_default="running", nullable=False),
        sa.Column("mode", sa.Text(), server_default="live", nullable=False),
        sa.Column("current_step_id", sa.Text(), nullable=True),
        sa.Column("snapshot_version", sa.Integer(), server_default="0", nullable=False),
        sa.Column("snapshot", sa.Text(), server_default="{}", nullable=False),
        sa.Column("snapshot_bytes", sa.Integer(), server_default="0", nullable=False),
        sa.Column("event_type", sa.Text(), server_default="", nullable=False),
        sa.Column("event_id", sa.Text(), nullable=True),
        sa.Column("dispatch_id", sa.Text(), nullable=True),
        sa.Column("parent_run_id", sa.Text(), nullable=True),
        sa.Column("parent_step_id", sa.Text(), nullable=True),
        sa.Column("deadline_at", sa.Float(), nullable=True),
        sa.Column("cancel_requested_at", sa.Float(), nullable=True),
        sa.Column("cancel_requested_by", sa.Text(), nullable=True),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), server_default="", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("started_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.Column("completed_at", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["artifact_sha256"], ["playbook_artifacts.artifact_sha256"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("run_id"),
        sa.CheckConstraint(
            "lifecycle IN ('running', 'paused', 'cancelling', 'completed', "
            "'failed', 'timed_out', 'cancelled')",
            name="ck_playbook_v2_runs_lifecycle",
        ),
        sa.CheckConstraint(
            "mode IN ('live', 'dry_run', 'shadow')", name="ck_playbook_v2_runs_mode"
        ),
    )
    op.create_index(
        "uq_playbook_v2_runs_dispatch_rule",
        "playbook_v2_runs",
        ["dispatch_id", "rule_id"],
        unique=True,
        sqlite_where=sa.text(_DISPATCH_WHERE),
        postgresql_where=sa.text(_DISPATCH_WHERE),
    )
    op.create_index(
        "idx_playbook_v2_runs_playbook", "playbook_v2_runs", ["playbook_id", "started_at"]
    )
    op.create_index("idx_playbook_v2_runs_lifecycle", "playbook_v2_runs", ["lifecycle"])
    op.create_index("idx_playbook_v2_runs_artifact", "playbook_v2_runs", ["artifact_sha256"])

    op.create_table(
        "playbook_step_receipts",
        sa.Column("receipt_id", sa.Text(), nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("artifact_sha256", sa.Text(), nullable=False),
        sa.Column("rule_id", sa.Text(), nullable=False),
        sa.Column("step_id", sa.Text(), nullable=False),
        sa.Column("step_kind", sa.Text(), nullable=False),
        sa.Column("iteration", sa.Integer(), server_default="-1", nullable=False),
        sa.Column("attempt", sa.Integer(), server_default="1", nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("snapshot_version", sa.Integer(), server_default="0", nullable=False),
        sa.Column("contract_fingerprint", sa.Text(), server_default="", nullable=False),
        sa.Column("principal", sa.Text(), server_default="{}", nullable=False),
        sa.Column("inputs", sa.Text(), server_default="{}", nullable=False),
        sa.Column("result", sa.Text(), server_default="{}", nullable=False),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("selected_transition", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("tokens_in", sa.Integer(), server_default="0", nullable=False),
        sa.Column("tokens_out", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("wait_id", sa.Text(), nullable=True),
        sa.Column("timed_out", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("cancelled_at", sa.Float(), nullable=True),
        sa.Column("started_at", sa.Float(), nullable=False),
        sa.Column("completed_at", sa.Float(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["playbook_v2_runs.run_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("receipt_id"),
        sa.UniqueConstraint(
            "run_id", "step_id", "iteration", "attempt",
            name="uq_playbook_step_receipts_attempt",
        ),
        sa.CheckConstraint(
            "outcome IN ('success', 'failure', 'skipped', 'timeout', 'cancelled', "
            "'operator_decision_required')",
            name="ck_playbook_step_receipts_outcome",
        ),
    )
    op.create_index(
        "idx_playbook_step_receipts_run", "playbook_step_receipts", ["run_id", "started_at"]
    )
    op.create_index(
        "idx_playbook_step_receipts_key", "playbook_step_receipts", ["idempotency_key"]
    )


def downgrade() -> None:
    op.drop_index("idx_playbook_step_receipts_key", table_name="playbook_step_receipts")
    op.drop_index("idx_playbook_step_receipts_run", table_name="playbook_step_receipts")
    op.drop_table("playbook_step_receipts")
    op.drop_index("idx_playbook_v2_runs_artifact", table_name="playbook_v2_runs")
    op.drop_index("idx_playbook_v2_runs_lifecycle", table_name="playbook_v2_runs")
    op.drop_index("idx_playbook_v2_runs_playbook", table_name="playbook_v2_runs")
    op.drop_index(
        "uq_playbook_v2_runs_dispatch_rule",
        table_name="playbook_v2_runs",
        sqlite_where=sa.text(_DISPATCH_WHERE),
        postgresql_where=sa.text(_DISPATCH_WHERE),
    )
    op.drop_table("playbook_v2_runs")
