"""add elevated flag to api_session_tokens for supervisor scope

Revision ID: c17d35836ed3
Revises: c5e2b7a9d3f4
Create Date: 2026-08-22 11:50:00.540930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c17d35836ed3'
down_revision: Union[str, Sequence[str], None] = 'c5e2b7a9d3f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_session_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('elevated', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_session_tokens', schema=None) as batch_op:
        batch_op.drop_column('elevated')

    # ### end Alembic commands ###
