"""token ledger cache columns and transcript checkpoints

Revision ID: c52f1a4fb6ba
Revises: 4d6f8a0b2c1e
Create Date: 2026-09-02 18:04:21.892346

Two additions, both in service of honest metrics:

* ``token_ledger.cache_read_tokens`` / ``cache_write_tokens`` — cache volume
  has always been folded into ``tokens_used`` but never broken out, so
  ``tokens_used - (input + output)`` was a six-figure "unattributed" number
  and the tokens/minute chart, which plots the split, showed a fraction of
  the real traffic.  Nullable, because every row written before this
  revision genuinely does not know the breakdown.
* ``transcript_checkpoints`` — the transcript watcher's byte high-water mark,
  keyed by transcript path rather than session id, so a relaunched session
  that adopts the same transcript file does not replay (and re-charge) its
  history.

The autogenerated diff also proposed renaming three pre-existing unnamed
constraints on ``agents``, ``tasks`` and ``task_dependencies``.  Those are
naming-convention drift that predates this change, not schema changes, and
rewriting them here would rebuild three large tables for nothing — so they
are deliberately left out.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c52f1a4fb6ba'
down_revision: str | Sequence[str] | None = '4d6f8a0b2c1e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'transcript_checkpoints',
        sa.Column('transcript_path', sa.Text(), nullable=False),
        sa.Column('byte_offset', sa.Integer(), nullable=False),
        sa.Column('last_entry_uuid', sa.Text(), nullable=True),
        sa.Column('session_id', sa.Text(), nullable=True),
        sa.Column('updated_at', sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint('transcript_path'),
    )
    with op.batch_alter_table('token_ledger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cache_read_tokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cache_write_tokens', sa.Integer(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('token_ledger', schema=None) as batch_op:
        batch_op.drop_column('cache_write_tokens')
        batch_op.drop_column('cache_read_tokens')

    op.drop_table('transcript_checkpoints')
