"""Database backend protocol (trait) defining all required operations.

Any database adapter must implement this protocol. The protocol is
organized by domain: projects, profiles, repos, tasks, dependencies,
agents, workspaces, tokens, results, events, playbook runs, archives,
and chat analyzer suggestions.

Usage::

    def needs_db(db: DatabaseBackend) -> None:
        ...  # type-checker ensures db has all required methods

To add a new backend (e.g. PostgreSQL), implement a class satisfying
every method in this protocol.
"""

from __future__ import annotations

from contextlib import AbstractAsyncContextManager
from typing import Protocol, runtime_checkable

from sqlalchemy.ext.asyncio import AsyncConnection

from src.database.queries.task_queries import TransitionResult

from src.models import (
    Agent,
    AgentProfile,
    AgentState,
    PlaybookRun,
    Project,
    ProjectStatus,
    RepoConfig,
    SessionRecord,
    Task,
    TaskAssignmentRoute,
    TaskCompletion,
    TaskStatus,
    Workflow,
    Workspace,
    WorkspaceMode,
)


@runtime_checkable
class DatabaseBackend(Protocol):
    """Trait defining the full database access contract.

    Every public method that the rest of the codebase calls on ``Database``
    must appear here.  Adapters (SQLite, PostgreSQL, …) implement this
    protocol so consumers are backend-agnostic.
    """

    async def update_task_description(
        self, task_id: str, description: str, *, expected_description: str | None = None,
        fence: dict | None = None,
    ) -> None: ...

    async def add_task_comment(
        self, task_id: str, body: str, *, author_kind: str, author_id: str,
        fence: dict | None = None,
    ) -> dict: ...

    async def list_task_comments(
        self, task_id: str, *, limit: int = 50, offset: int = 0, project_id: str | None = None,
    ) -> dict: ...

    # --- Lifecycle ---

    async def initialize(self) -> None:
        """Create tables, run migrations, and prepare the connection."""
        ...

    async def close(self) -> None:
        """Gracefully shut down the database connection."""
        ...

    # --- Projects ---

    async def create_project(self, project: Project) -> None: ...
    async def get_project(self, project_id: str) -> Project | None: ...
    async def list_projects(self, status: ProjectStatus | None = None) -> list[Project]: ...
    async def update_project(self, project_id: str, **kwargs) -> None: ...
    async def delete_project(self, project_id: str) -> None: ...

    # --- Agent Profiles ---

    async def create_profile(self, profile: AgentProfile) -> None: ...
    async def get_profile(self, profile_id: str) -> AgentProfile | None: ...
    async def list_profiles(self) -> list[AgentProfile]: ...
    async def update_profile(self, profile_id: str, **kwargs) -> None: ...
    async def upsert_profile(self, profile: AgentProfile) -> str: ...
    async def delete_profile(self, profile_id: str) -> None: ...

    # --- Repos ---

    async def create_repo(self, repo: RepoConfig) -> None: ...
    async def get_repo(self, repo_id: str) -> RepoConfig | None: ...
    async def list_repos(self, project_id: str | None = None) -> list[RepoConfig]: ...
    async def update_repo(self, repo_id: str, **kwargs) -> None: ...
    async def delete_repo(self, repo_id: str) -> None: ...

    # --- Tasks ---

    async def create_task(self, task: Task, *, conn=None) -> None: ...
    async def get_task(self, task_id: str) -> Task | None: ...
    async def list_tasks(
        self,
        project_id: str | None = None,
        status: TaskStatus | None = None,
        *,
        labels: list[str] | None = None,
        any_label: list[str] | None = None,
    ) -> list[Task]: ...
    async def list_active_tasks(
        self,
        project_id: str | None = None,
        exclude_statuses: set[TaskStatus] | None = None,
    ) -> list[Task]: ...
    async def list_active_tasks_all_projects(self) -> list[Task]: ...
    async def count_tasks_by_status(
        self,
        project_id: str | None = None,
    ) -> dict[str, int]: ...
    async def update_task(self, task_id: str, **kwargs) -> None: ...
    async def append_task_attachment(self, task_id: str, path: str) -> list[str] | None: ...
    async def remove_task_attachment(self, task_id: str, path: str) -> list[str] | None: ...
    async def transition_task(
        self,
        task_id: str,
        new_status: TaskStatus,
        *,
        context: str = "",
        **kwargs,
    ) -> set[str]: ...
    async def delete_task(
        self, task_id: str, *, cascade: bool = False, conn=None
    ) -> "TransitionResult | None": ...
    async def get_task_updated_at(self, task_id: str) -> float | None: ...
    async def get_task_assignment_route(
        self, task_id: str, *, conn=None
    ) -> TaskAssignmentRoute | None: ...
    async def list_task_assignment_routes(
        self, task_ids, *, conn=None
    ) -> list[TaskAssignmentRoute]: ...
    async def upsert_task_assignment_routes(
        self, routes, *, conn
    ) -> None: ...
    async def get_task_created_at(self, task_id: str) -> float | None: ...
    async def add_task_context(
        self,
        task_id: str,
        *,
        type: str,
        label: str,
        content: str,
    ) -> str: ...
    async def get_task_contexts(self, task_id: str) -> list[dict]: ...
    async def set_task_meta(self, task_id: str, key: str, value) -> None: ...
    async def get_task_meta(self, task_id: str, key: str): ...
    async def get_all_task_meta(self, task_id: str) -> dict: ...
    async def delete_task_meta(self, task_id: str, key: str) -> None: ...
    async def task_ids_with_meta(self, task_ids: list[str], key: str) -> set[str]: ...
    async def add_task_label(self, task_id: str, label: str) -> None: ...
    async def remove_task_label(self, task_id: str, label: str) -> list[str]: ...
    async def get_task_labels(self, task_id: str) -> list[str]: ...
    async def get_subtasks(self, parent_task_id: str) -> list[Task]: ...
    async def get_task_tree(self, root_task_id: str, *, max_depth: int = 4) -> dict | None: ...
    async def get_parent_tasks(
        self,
        project_id: str,
        *,
        labels: list[str] | None = None,
        any_label: list[str] | None = None,
    ) -> list[Task]: ...

    # --- Hierarchy (swarm work model, spec Part I §4-§8) ---
    #
    # ``set_parent`` / ``set_parent_bulk`` are the *only* writers of
    # ``tasks.parent_task_id``; both take a caller-owned ``conn`` because the
    # edge, the pointer, the blocked-state recompute and the settlement are
    # one transaction.

    async def get_children(
        self,
        parent_id: str,
        *,
        recursive: bool = False,
        status: str | None = None,
        limit: int | None = None,
        offset: int = 0,
    ) -> list[Task]: ...
    async def get_children_summary(self, task_id: str) -> dict | None: ...
    async def set_parent(
        self,
        task_id: str,
        parent_id: str | None,
        *,
        conn,
        description: str | None = None,
    ) -> "TransitionResult": ...
    async def set_parent_bulk(
        self, child_ids: list[str], parent_id: str, *, conn
    ) -> tuple[set[str], list[str]]: ...
    async def settle_containers(
        self, seeds: set[str], *, conn, depth: int = 0
    ) -> "TransitionResult": ...
    async def open_children(self, task_id: str, *, conn=None) -> list[str]: ...
    async def subtree_ids(self, root_id: str, *, conn) -> list[str]: ...
    async def abandon_subtree(self, task_id: str, *, conn) -> "TransitionResult": ...
    async def manually_paused_descendants(self, task_id: str, *, conn) -> list[str]: ...
    async def live_descendant_sessions(
        self, task_id: str, *, conn, exclude_root: bool = False
    ) -> list[tuple[str, str]]: ...

    # --- Transactions ---

    def immediate(self) -> "AbstractAsyncContextManager[AsyncConnection]": ...

    # --- Blocked-state projection (work-graph design §4) ---

    async def recompute_blocked(self, seed_task_ids: set[str], *, conn) -> set[str]: ...
    async def recompute_blocked_waves(
        self,
        seed_task_ids: set[str],
        *,
        conn,
        extra_waves: list[set[str]] | None = None,
    ) -> set[str]: ...
    async def recompute_all_blocked(self) -> set[str]: ...
    async def log_blocked_flips(self, flipped: set[str]) -> None: ...
    async def get_blocked_map(self, task_ids: list[str] | None = None) -> dict[str, bool]: ...
    async def evaluate_blocked(self, task_ids: list[str] | None = None) -> dict[str, bool]: ...
    async def get_ready_frontier(
        self,
        project_id: str,
        *,
        labels: list[str] | None = None,
        any_label: list[str] | None = None,
    ) -> list[Task]: ...
    async def tasks_with_graph_blockers(self, task_ids: list[str]) -> set[str]: ...
    async def find_dead_conditional_tasks(self) -> list[tuple[str, str]]: ...

    # --- Dependencies ---

    async def add_dependency(
        self,
        task_id: str,
        depends_on: str,
        dep_type: str = "blocks",
        *,
        description: str | None = None,
        conn=None,
    ) -> set[str] | None: ...
    async def get_dependencies(
        self, task_id: str, dep_types: frozenset[str] | None = None
    ) -> set[str]: ...
    async def get_typed_dependencies(self, task_id: str) -> list[tuple[str, str]]: ...
    async def get_typed_dependencies_detailed(self, task_id: str) -> list[dict]: ...
    async def get_all_dependencies(
        self, dep_types: frozenset[str] | None = None
    ) -> dict[str, set[str]]: ...
    async def get_parent_child_edges(self) -> dict[str, set[str]]: ...
    async def are_dependencies_met(self, task_id: str) -> bool: ...
    async def get_stuck_defined_tasks(self, threshold_seconds: int) -> list[Task]: ...
    async def get_stuck_active_tasks(
        self,
        assigned_threshold_seconds: int,
        in_progress_threshold_seconds: int,
        now: float,
        project_id: str | None = None,
    ) -> list[Task]: ...
    async def get_blocking_dependencies(
        self,
        task_id: str,
    ) -> list[tuple[str, str, str, str, str]]: ...
    async def get_dependents(
        self, task_id: str, dep_types: frozenset[str] | None = None
    ) -> set[str]: ...
    async def get_dependency_map_for_tasks(
        self,
        task_ids: list[str],
    ) -> dict[str, dict]: ...
    async def remove_dependency(
        self, task_id: str, depends_on: str, dep_type: str | None = None
    ) -> None: ...
    async def remove_all_dependencies_on(self, depends_on_task_id: str) -> None: ...

    # --- Agents ---

    async def create_agent(self, agent: Agent) -> None: ...
    async def create_automatic_agent(self, agent: Agent) -> bool: ...
    async def get_agent(self, agent_id: str) -> Agent | None: ...
    async def list_agents(
        self, state: AgentState | None = None, *, include_deleted: bool = False
    ) -> list[Agent]: ...
    async def update_agent(self, agent_id: str, **kwargs) -> None: ...
    async def delete_agent(self, agent_id: str) -> None: ...
    async def soft_delete_agent(self, agent_id: str) -> bool: ...

    # --- Workspaces ---

    async def create_workspace(self, workspace: Workspace) -> None: ...
    async def get_workspace(self, workspace_id: str) -> Workspace | None: ...
    async def get_workspace_by_name(
        self,
        project_id: str,
        name: str,
    ) -> Workspace | None: ...
    async def list_workspaces(
        self,
        project_id: str | None = None,
    ) -> list[Workspace]: ...
    async def delete_workspace(self, workspace_id: str) -> None: ...
    async def update_workspace(self, workspace_id: str, **fields) -> int: ...
    async def acquire_workspace(
        self,
        project_id: str,
        agent_id: str,
        task_id: str,
        preferred_workspace_id: str | None = None,
        lock_mode: WorkspaceMode = WorkspaceMode.EXCLUSIVE,
    ) -> Workspace | None: ...
    async def find_worktree_base(
        self,
        project_id: str,
        kind_id: str,
    ) -> Workspace | None: ...
    async def list_slots_for_base(self, base_workspace_id: str) -> list[Workspace]: ...
    async def release_workspace(self, workspace_id: str) -> None: ...
    async def release_workspaces_for_agent(self, agent_id: str, *, conn=None) -> int: ...
    async def release_workspaces_for_task(self, task_id: str) -> int: ...
    async def get_workspace_for_task(self, task_id: str) -> Workspace | None: ...
    async def get_workspace_for_agent(self, agent_id: str) -> Workspace | None: ...
    async def get_project_workspace_path(self, project_id: str) -> str | None: ...
    async def count_available_workspaces(
        self,
        project_id: str,
        *,
        worktree_slot_cap: int | None = None,
    ) -> int: ...
    async def count_free_slots(self, project_id: str, *, worktree_slot_cap: int) -> int: ...

    async def get_task_session_attempt(self, attempt_id: str) -> dict | None: ...
    async def list_task_session_attempts(
        self, task_id: str, *, project_id: str | None = None, since: float | None = None,
    ) -> list[dict]: ...
    async def finish_task_session_attempt(
        self, session_id, *, task_id=None, ended_at=None, end_reason=None,
        outcome=None, state="stopped", conn=None,
    ) -> int: ...
    async def record_task_session_outcome(
        self, task_id, outcome, *, session_id=None, conn=None,
    ) -> None: ...

    # --- Sessions (session-runtime spec §2.3) ---

    async def create_session(
        self, session: SessionRecord, *, release_agent_reservation: bool = False
    ) -> None: ...
    async def get_session(self, session_id: str) -> SessionRecord | None: ...
    async def get_session_with_profile(
        self, session_id: str
    ) -> tuple[SessionRecord | None, AgentProfile | None]: ...
    async def get_session_by_name(self, name: str) -> SessionRecord | None: ...
    async def get_session_for_task(self, task_id: str) -> SessionRecord | None: ...
    async def list_sessions(
        self,
        *,
        state: str | None = None,
        states: list[str] | tuple[str, ...] | None = None,
        lifecycle: str | None = None,
        project_id: str | None = None,
        name: str | None = None,
        live_only: bool = False,
        agent_id: str | None = None,
        claim_phase: str | None = None,
    ) -> list[SessionRecord]: ...
    async def update_session(self, session_id: str, **fields) -> int: ...
    async def bump_session_restarts(self, session_id: str) -> int: ...
    async def touch_session_activity(self, session_id: str, ts: float) -> None: ...
    async def delete_session(self, session_id: str) -> None: ...

    # --- Token Ledger ---

    async def record_token_usage(
        self,
        project_id: str | None,
        agent_id: str,
        task_id: str,
        tokens: int,
        *,
        model: str | None = None,
        input_tokens: int | None = None,
        output_tokens: int | None = None,
    ) -> None: ...
    async def get_cost_rollup(
        self,
        *,
        project_id: str | None = None,
        since_ts: float | None = None,
        group_by: str = "project",
    ) -> list[dict]: ...
    async def get_project_token_usage(
        self,
        project_id: str,
        since: float | None = None,
    ) -> int: ...
    async def get_token_audit(
        self,
        days: int = 7,
        project_id: str | None = None,
    ) -> dict: ...

    # --- Task Results ---

    async def save_task_result(
        self,
        task_id: str,
        agent_id: str,
        output,
    ) -> None: ...
    async def get_task_result(self, task_id: str) -> dict | None: ...
    async def get_task_results(self, task_id: str) -> list[dict]: ...
    async def save_task_completion(self, completion: TaskCompletion) -> None: ...
    async def get_task_completion(self, task_id: str) -> TaskCompletion | None: ...
    async def get_task_completions(self, task_id: str) -> list[TaskCompletion]: ...

    # --- Events ---

    async def log_event(
        self,
        event_type: str,
        project_id: str | None = None,
        task_id: str | None = None,
        agent_id: str | None = None,
        payload: str | None = None,
    ) -> None: ...
    async def get_recent_events(self, limit: int = 50) -> list[dict]: ...
    async def max_event_id(self) -> int: ...
    async def count_events_after(self, seq: int, *, event_type: str, project_id: str) -> int: ...

    # --- Claims (swarm work model, spec §10, §11.2) ---

    async def take_claim_slot(
        self, conn, session_id: str, *, now: float, cap: int | None
    ) -> tuple[str, SessionRecord | None]: ...
    async def release_claim_slot(self, conn, session_id: str) -> None: ...
    async def select_ready_for_profile(
        self,
        conn,
        *,
        project_id: str,
        profile_id: str,
        default_profile_id: str | None,
        agent_id: str,
        task_id: str | None = None,
    ) -> str | None: ...
    async def take_task(self, conn, task_id: str, *, agent_id: str, now: float) -> Task | None: ...
    async def record_holder(
        self,
        conn,
        *,
        session_id: str,
        task_id: str,
        claim_epoch: int,
        agent_id: str,
        work_dir: str,
        now: float,
    ) -> Workspace | None: ...
    async def activate_claim(
        self, session_id: str, task_id: str, *, epoch: int, now: float, conn=None
    ) -> SessionRecord | None: ...
    async def release_claim(
        self,
        session_id: str,
        *,
        task_status: TaskStatus,
        context: str,
        now: float,
        result: str = "released",
        needs_attention: str | None = None,
        expected_task_id: str | None = None,
        expected_claim_epoch: int | None = None,
        drain_after_release: bool = False,
        conn=None,
    ) -> "TransitionResult": ...
    async def terminate_pool_session(
        self,
        session_id: str,
        *,
        reason: str,
        task_status: TaskStatus = TaskStatus.READY,
        conn=None,
    ) -> "TransitionResult": ...
    async def bump_claim_epoch(self, task_id: str, *, conn=None) -> int: ...
    async def reserve_filing(self, conn, task_id: str, *, max_filings: int) -> bool: ...
    async def count_ready_by_profile(self, project_id: str) -> dict[str | None, int]: ...

    # --- Hooks / Hook Runs removed (playbooks spec §13 Phase 3) ---

    # --- Playbook Runs ---

    async def create_playbook_run(self, run: PlaybookRun) -> None: ...
    async def get_playbook_run(self, run_id: str) -> PlaybookRun | None: ...
    async def list_playbook_runs(
        self,
        playbook_id: str | None = None,
        status: str | None = None,
        limit: int = 50,
    ) -> list[PlaybookRun]: ...
    async def update_playbook_run(self, run_id: str, **kwargs) -> None: ...
    async def delete_playbook_run(self, run_id: str) -> None: ...
    async def get_playbook_run_by_event(
        self, playbook_id: str, event_id: str
    ) -> PlaybookRun | None: ...

    # --- Workflows ---

    async def create_workflow(self, workflow: Workflow) -> None: ...
    async def get_workflow(self, workflow_id: str) -> Workflow | None: ...
    async def list_workflows(
        self,
        project_id: str | None = None,
        playbook_id: str | None = None,
        status: str | None = None,
        limit: int = 50,
    ) -> list[Workflow]: ...
    async def update_workflow(self, workflow_id: str, **kwargs) -> None: ...
    async def update_workflow_status(
        self,
        workflow_id: str,
        new_status: str,
        *,
        completed_at: float | None = None,
    ) -> None: ...
    async def add_workflow_task(self, workflow_id: str, task_id: str) -> None: ...
    async def delete_workflow(self, workflow_id: str) -> None: ...

    # --- Atomic Operations ---

    async def assign_task_to_agent(self, task_id: str, agent_id: str) -> bool: ...
    async def reserve_idle_agent(self, agent_id: str) -> bool: ...
    async def release_agent_reservation(
        self, agent_id: str, *, expected_heartbeat: float | None
    ) -> bool: ...
    async def release_agent_for_task(self, agent_id: str, task_id: str) -> bool: ...

    # --- Archived Tasks ---

    async def archive_task(self, task_id: str) -> bool: ...
    async def archive_completed_tasks(
        self,
        project_id: str | None = None,
    ) -> list[str]: ...
    async def archive_old_terminal_tasks(
        self,
        statuses: list[str],
        older_than_seconds: float,
    ) -> list[str]: ...
    async def list_archived_tasks(
        self,
        project_id: str | None = None,
        limit: int = 50,
    ) -> list[dict]: ...
    async def get_archived_task(self, task_id: str) -> dict | None: ...
    async def delete_archived_task(self, task_id: str) -> bool: ...
    async def count_archived_tasks(
        self,
        project_id: str | None = None,
    ) -> int: ...

    # --- Chat Analyzer Suggestions ---

    async def create_chat_analyzer_suggestion(
        self,
        project_id: str,
        channel_id: int,
        suggestion_type: str,
        suggestion_text: str,
        suggestion_hash: str,
        context_snapshot: str | None = None,
    ) -> int: ...
    async def create_suppressed_chat_analyzer_suggestion(
        self,
        project_id: str,
        channel_id: int,
        suggestion_type: str,
        suggestion_text: str,
        suggestion_hash: str,
        suppressed_by: str,
        context_snapshot: str | None = None,
    ) -> int: ...
    async def resolve_chat_analyzer_suggestion(
        self,
        suggestion_id: int,
        status: str,
    ) -> None: ...
    async def get_suggestion_hash_exists(
        self,
        project_id: str,
        suggestion_hash: str,
    ) -> bool: ...
    async def count_recent_suggestions(
        self,
        project_id: str,
        since: float,
    ) -> int: ...
    async def get_suggestion(self, suggestion_id: int) -> dict | None: ...
    async def get_recent_suggestions(
        self,
        channel_id: int,
        hours: int = 24,
    ) -> list[dict]: ...
    async def update_suggestion_status(
        self,
        suggestion_id: int,
        status: str,
        resolved_at: float | None = None,
    ) -> None: ...
    async def get_last_dismiss_time(
        self,
        project_id: str,
        channel_id: int,
    ) -> float | None: ...
    async def get_analyzer_suggestion_stats(
        self,
        project_id: str | None = None,
        since: float | None = None,
    ) -> dict: ...
    async def get_analyzer_suggestion_history(
        self,
        project_id: str | None = None,
        limit: int = 20,
    ) -> list[dict]: ...

    # --- Completed-turn agent questions ---
    async def create_agent_question(self, **values) -> bool: ...
    async def get_agent_question(self, question_id: str) -> dict | None: ...
    async def list_agent_questions(self, project_id=None, session_id=None, pending_only=True) -> list[dict]: ...
    async def transition_agent_question(self, question_id, expected_states, **values) -> bool: ...
    async def mark_agent_question_notified(self, question_id, channel_id, message_id) -> None: ...
    async def claim_agent_question_notification(self, question_id, now) -> bool: ...
    async def queue_task_recovery_notifications(self) -> int: ...
    async def decide_task_recovery(self, task_id, incident_id, decision, reason, *, author_kind, author_id, project_id=None, stopped_session=None) -> dict: ...

    async def queue_agent_question_supervisor(self, question_id, body, recipient, now) -> None: ...
    async def claim_agent_question_delivery(self, question_id, token, now) -> bool: ...
    async def finish_agent_question_delivery(self, question_id, token, *, delivered, now) -> bool: ...
    async def get_message_discord_receipt(self, message_id) -> dict | None: ...
    async def mark_message_discord_notified(self, message_id, channel_id, discord_message_id) -> None: ...
    async def ensure_message_discord_notification(self, message_id) -> None: ...
    async def list_pending_message_discord_notifications(self, limit=100) -> list[str]: ...
    def agent_question_delivery_guard(self, question_id, token): ...
    async def record_agent_question_delivery(self, conn, question_id, token, session_id, now): ...
