#!/usr/bin/env python3
"""Generate or verify the per-command pages under ``docs/reference/playbook-commands``.

Every playbook command is a typed contract in
``src/commands/contracts/registry.py``.  The half of its documentation that
the contract already knows — title, summary, parameters, result shape,
outcomes, declared effects and the execution contract itself — is generated
here and lives between ``<!-- aq:generated:start -->`` and
``<!-- aq:generated:end -->``.  Everything outside those markers is
hand-written and is preserved on every regeneration.

Usage::

    python scripts/gen-command-docs.py            # write the pages and the index
    python scripts/gen-command-docs.py --check    # fail when a page is stale

``tests/test_command_docs.py`` runs the check, so drift fails CI.
"""

from __future__ import annotations

import argparse
import json
import sys
from functools import partial
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "docs" / "reference" / "playbook-commands"
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

START = "<!-- aq:generated:start -->"
END = "<!-- aq:generated:end -->"
BANNER = "<!-- Generated by scripts/gen-command-docs.py. Edit outside these markers only. -->"

#: Index sections, in the order the README lists them.  Every registered
#: command lands in exactly one of them; ``other`` is the declared remainder,
#: not an accident.
FAMILIES: tuple[tuple[str, str], ...] = (
    ("tasks", "Tasks, gates and routing"),
    ("memory", "Memory"),
    ("messaging", "Messaging"),
    ("delivery", "Delivery"),
    ("escalation", "Escalation"),
    ("integration", "Integration"),
    ("other", "Other"),
)

_TASK_COMMANDS = frozenset(
    {
        "add_dependency",
        "create_task",
        "edit_task",
        "ensure_task",
        "gate_create",
        "gate_resolve",
        "get_downstream_tasks",
        "get_task",
        "list_tasks",
        "stop_task",
        "task_batch_commit",
        "task_recovery_notify",
        "task_route",
        "task_route_options",
    }
)
_MEMORY_COMMANDS = frozenset(
    {"count_project_memory_files", "memory_save", "memory_search", "read_project_memory_file"}
)
_MESSAGING_COMMANDS = frozenset({"message_send"})


class MarkerError(RuntimeError):
    """A page exists but no longer carries the generated-block markers."""


def family(name: str) -> str:
    """The index section a command belongs to."""
    if name in _TASK_COMMANDS:
        return "tasks"
    if name in _MEMORY_COMMANDS:
        return "memory"
    if name in _MESSAGING_COMMANDS:
        return "messaging"
    if name.startswith("delivery_"):
        return "delivery"
    if name.startswith("escalation_"):
        return "escalation"
    if name.startswith("integration_"):
        return "integration"
    return "other"


# ---------------------------------------------------------------- rendering


def cell(value: str) -> str:
    """Escape a value for one Markdown table cell."""
    return value.replace("|", "\\|").replace("\n", " ").strip()


def code(value: str) -> str:
    return f"`{cell(value)}`"


def _grouped(label: str) -> str:
    """Parenthesise a union so that ``X | null`` inside an array stays readable."""
    return f"({label})" if " | " in label else label


def type_label(schema: dict[str, Any]) -> str:
    """A readable type for one JSON-schema node, without Markdown."""
    if not schema:
        return "any"
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    if "enum" in schema:
        return " | ".join(json.dumps(value, ensure_ascii=False) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(type_label(option) for option in schema["anyOf"])
    kind = schema.get("type")
    if kind == "array":
        return f"{_grouped(type_label(schema.get('items') or {}))}[]"
    if isinstance(kind, list):
        return " | ".join(str(item) for item in kind)
    if isinstance(kind, str):
        return kind
    return "any"


def fields(schema: dict[str, Any]) -> list[dict[str, Any]]:
    """One row per property of an object schema, in declaration order."""
    required = set(schema.get("required") or ())
    rows = []
    for name, node in (schema.get("properties") or {}).items():
        rows.append(
            {
                "name": name,
                "type": type_label(node),
                "required": name in required,
                "default": node.get("default", ...),
                "description": str(node.get("description") or ""),
            }
        )
    return rows


def _default_label(value: Any) -> str:
    return "—" if value is ... else code(json.dumps(value, ensure_ascii=False, default=str))


def _parameter_table(schema: dict[str, Any], labels: dict[str, str]) -> list[str]:
    rows = fields(schema)
    if not rows:
        return ["This command takes no parameters."]
    lines = [
        "| Parameter | Type | Required | Default | Description |",
        "|---|---|---|---|---|",
    ]
    for row in rows:
        description = row["description"] or labels.get(row["name"], "") or "—"
        lines.append(
            f"| {code(row['name'])} | {code(row['type'])} "
            f"| {'yes' if row['required'] else 'no'} | {_default_label(row['default'])} "
            f"| {cell(description)} |"
        )
    return lines


def _result_table(schema: dict[str, Any], labels: dict[str, str]) -> list[str]:
    rows = fields(schema)
    if not rows:
        return ["This command returns no result fields."]
    lines = ["| Field | Type | Description |", "|---|---|---|"]
    for row in rows:
        description = row["description"] or labels.get(row["name"], "") or "—"
        lines.append(f"| {code(row['name'])} | {code(row['type'])} | {cell(description)} |")
    return lines


def _definition_tables(*schemas: dict[str, Any]) -> list[str]:
    """Tables for the nested models the argument or result schemas reference."""
    definitions: dict[str, dict[str, Any]] = {}
    for schema in schemas:
        for name, node in (schema.get("$defs") or {}).items():
            definitions[name] = node
    if not definitions:
        return []
    lines = ["", "## Nested objects", ""]
    for name in sorted(definitions):
        lines.append(f"### {code(name)}")
        lines.append("")
        lines.extend(_result_table(definitions[name], {}))
        lines.append("")
    return lines[:-1]


def _idempotency_label(execution: Any) -> str:
    mode = execution.idempotency.mode
    if mode == "keyed":
        return f"keyed on {code(execution.idempotency.key_field or '')}"
    return mode


def _effect_rows(contract: Any) -> list[str]:
    """The effect table the playbook graph renders for this command."""
    from src.playbooks.explanation import canonical_effect, render_effect

    effects = contract.execution.effects
    header = ["| Effect | Subject | Condition |", "|---|---|---|"]
    if not effects:
        fallback = canonical_effect(contract)
        return [
            (
                "This command declares no effect clause, so the playbook graph falls back "
                "to its side-effect class and argument names:"
            ),
            "",
            *header,
            f"| {cell(fallback.text)} | — | always |",
        ]
    lines = list(header)
    for clause in effects:
        rendered = render_effect(clause, {}, contract.presentation)
        lines.append(
            f"| {cell(rendered.text)} | {code(clause.subject.value)} "
            f"| {cell(rendered.condition or 'always')} |"
        )
    return lines


def _source_link(contract: Any) -> str:
    """A link to the module the contract's argument model is declared in."""
    module = sys.modules[contract.execution.args_model.__module__]
    path = Path(module.__file__ or "").resolve()
    if not path.is_relative_to(ROOT):
        return code(contract.execution.args_model.__module__)
    relative = path.relative_to(ROOT)
    return f"[`{relative}`](../../../{relative})"


def generated_block(name: str, contract: Any) -> str:
    """The registry-derived half of one command page, markers included."""
    execution = contract.execution
    presentation = contract.presentation
    args_schema = execution.args_model.model_json_schema(mode="validation")
    result_schema = execution.result_model.model_json_schema(mode="validation")

    headline = f"**{presentation.title}.**"
    if presentation.summary:
        headline = f"{headline} {presentation.summary}"
    timeout = code(f"{execution.timeout_seconds}s") if execution.timeout_seconds else "none"
    lines = [
        START,
        BANNER,
        "",
        f"# {code(name)}",
        "",
        headline,
        "",
        "| Property | Value |",
        "|---|---|",
        f"| Capability | {code(execution.capability)} |",
        f"| Side effect | {code(execution.side_effect.value)} |",
        f"| Idempotency | {_idempotency_label(execution)} |",
        f"| Retry safe | {'yes' if execution.retry_safe else 'no'} |",
        f"| Timeout | {timeout} |",
        f"| Preview | {'supported' if execution.supports_preview else 'not supported'} |",
        f"| Defined in | {_source_link(contract)} |",
        f"| Contract fingerprint | {code(contract.fingerprint())} |",
        "",
        "## Parameters",
        "",
    ]
    lines += _parameter_table(args_schema, presentation.arg_labels)
    if execution.sensitive_args:
        redacted = ", ".join(code(field) for field in sorted(execution.sensitive_args))
        lines += ["", f"Redacted in receipts and explanations: {redacted}."]
    lines += ["", "## Result", ""]
    lines += _result_table(result_schema, presentation.result_labels)
    if execution.receipt_projection:
        projected = ", ".join(code(field) for field in execution.receipt_projection)
        lines += ["", f"Projected into the run receipt: {projected}."]
    if execution.sensitive_result_fields:
        redacted = ", ".join(code(field) for field in sorted(execution.sensitive_result_fields))
        lines += ["", f"Redacted in receipts and explanations: {redacted}."]
    lines += _definition_tables(args_schema, result_schema)
    lines += ["", "## Outcomes", "", "| Outcome | Classification | Meaning |", "|---|---|---|"]
    for outcome in sorted(execution.outcomes, key=lambda spec: spec.name):
        meaning = presentation.outcome_labels.get(outcome.name, "") or "—"
        lines.append(
            f"| {code(outcome.name)} | {outcome.classification.value} | {cell(meaning)} |"
        )
    lines += ["", "## Declared effects", ""]
    lines += _effect_rows(contract)
    lines += ["", END]
    return "\n".join(lines)


HANDWRITTEN_SECTIONS: tuple[tuple[str, str], ...] = (
    ("Purpose", "TODO: what this command is for, in the reader's terms."),
    ("When a playbook uses it", "TODO: the situations a playbook step reaches for it."),
    (
        "How it works internally",
        "TODO: step by step through the executor and handler, with file references.",
    ),
    (
        "Side effects and persistence",
        "TODO: what it writes, which tables or files hold it, and what survives a restart.",
    ),
    (
        "Failure modes and diagnostics",
        "TODO: each failure outcome, what causes it, and the command that diagnoses it.",
    ),
    ("Example step", "TODO: a realistic playbook step that calls this command."),
)


def handwritten_stub() -> str:
    """The hand-written half of a new page: headings with one TODO each."""
    lines: list[str] = []
    for heading, todo in HANDWRITTEN_SECTIONS:
        lines += ["", f"## {heading}", "", todo]
    return "\n".join(lines) + "\n"


def splice(existing: str, block: str) -> str:
    """Replace the generated block in *existing*, keeping everything else."""
    start = existing.find(START)
    end = existing.find(END)
    if start < 0 or end < start:
        raise MarkerError("generated markers are missing or out of order")
    return existing[:start] + block + existing[end + len(END) :]


def render_page(name: str, contract: Any, existing: str | None) -> str:
    block = generated_block(name, contract)
    if existing is None:
        return block + "\n" + handwritten_stub()
    return splice(existing, block)


INDEX_INTRO = """\
# Playbook commands

The commands a playbook step may call, one page each. Every page is half
generated and half hand-written: the contract facts below the title come from
the command registry, and the prose around them is written by hand.

## How to read a page

Each page opens with a generated block — parameters, result fields, outcomes
and the execution contract, taken from
[`src/commands/contracts/registry.py`](../../../src/commands/contracts/registry.py)
— and continues with hand-written sections that explain what the command is
for, how it works internally, what it persists, and how it fails.

Never edit between the `aq:generated` markers; run
[`scripts/gen-command-docs.py`](../../../scripts/gen-command-docs.py) instead.
See [code generation](../../contributing/codegen.md#the-playbook-command-pages).
"""


def render_index(contracts: dict[str, Any], existing: str | None) -> str:
    grouped: dict[str, list[str]] = {key: [] for key, _ in FAMILIES}
    for name in sorted(contracts):
        grouped[family(name)].append(name)

    lines = [START, BANNER, "", "## The commands", "", f"{len(contracts)} commands are registered."]
    for key, heading in FAMILIES:
        names = grouped[key]
        if not names:
            continue
        lines += [
            "",
            f"### {heading}",
            "",
            "| Command | Title | Summary |",
            "|---|---|---|",
        ]
        for name in names:
            presentation = contracts[name].presentation
            lines.append(
                f"| [{code(name)}]({name}.md) | {cell(presentation.title)} "
                f"| {cell(presentation.summary) or '—'} |"
            )
    lines += ["", END]
    block = "\n".join(lines)
    if existing is None:
        return INDEX_INTRO + "\n" + block + "\n"
    return splice(existing, block)


# ------------------------------------------------------------------ driving


def _display(path: Path) -> str:
    """A repository-relative path when there is one — ``--output`` may be anywhere."""
    return str(path.relative_to(ROOT)) if path.is_relative_to(ROOT) else str(path)


def _read(path: Path) -> str | None:
    return path.read_text(encoding="utf-8") if path.is_file() else None


def _rendered(path: Path, render) -> str:
    """Render one page, naming the file in a marker failure."""
    try:
        return render(_read(path))
    except MarkerError as error:
        raise MarkerError(f"{_display(path)}: {error}") from error


def render_all(output: Path) -> dict[Path, str]:
    """The full desired content of the section, keyed by path."""
    from src.commands.contracts import CONTRACTS

    contracts = {name: CONTRACTS.require(name).contract for name in sorted(CONTRACTS.names())}
    pages: dict[Path, str] = {}
    for name, contract in contracts.items():
        path = output / f"{name}.md"
        pages[path] = _rendered(path, partial(render_page, name, contract))
    index = output / "README.md"
    pages[index] = _rendered(index, partial(render_index, contracts))
    return pages


def orphans(output: Path, expected: dict[Path, str]) -> list[Path]:
    """Committed pages that no registered command owns."""
    if not output.is_dir():
        return []
    return sorted(path for path in output.glob("*.md") if path not in expected)


def check(output: Path) -> list[str]:
    """Return one readable problem per stale, missing or orphaned page."""
    problems: list[str] = []
    try:
        expected = render_all(output)
    except MarkerError as error:
        return [str(error)]
    for path, content in sorted(expected.items()):
        current = _read(path)
        if current is None:
            problems.append(f"{_display(path)}: missing")
        elif current != content:
            problems.append(f"{_display(path)}: generated block is stale")
    for path in orphans(output, expected):
        problems.append(f"{_display(path)}: no command of that name is registered")
    return problems


def write(output: Path) -> list[Path]:
    """Write every page, returning the ones that changed."""
    expected = render_all(output)
    output.mkdir(parents=True, exist_ok=True)
    changed = []
    for path, content in sorted(expected.items()):
        if _read(path) != content:
            path.write_text(content, encoding="utf-8")
            changed.append(path)
    return changed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail when a page is stale.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    output = args.output.resolve()

    if args.check:
        problems = check(output)
        if problems:
            print("command documentation is stale:")
            print("\n".join(f"  - {problem}" for problem in problems))
            print(f"run: python {_display(Path(__file__).resolve())}")
            return 1
        pages = len(list(output.glob("*.md"))) - 1
        print(f"command documentation current: {pages} command pages")
        return 0

    try:
        changed = write(output)
    except MarkerError as error:
        print(error)
        return 1
    for path in changed:
        print(f"wrote {_display(path)}")
    print(f"{len(changed)} file(s) changed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
