#!/usr/bin/env bash
# Regenerate the typed Python API client from the daemon's OpenAPI spec.
#
# Usage:
#   ./scripts/regenerate-api-client.sh --offline    # build the spec in-process
#   ./scripts/regenerate-api-client.sh              # fetch it from a running daemon
#   ./scripts/regenerate-api-client.sh --from-file  # use saved openapi.json
#
# --offline is the canonical path: the spec is a pure function of the
# checkout, so it needs no daemon and cannot pick up another instance's state.
#
# Prerequisites:
#   pip install 'openapi-python-client==0.29.0' 'ruff==0.16.5'   # or: pip install -e '.[dev]'
#
# The generator version is pinned below and checked before anything is
# generated.  The whole client tree -- including the boilerplate README.md the
# generator writes -- is a function of the generator version, so an unpinned
# generator makes regeneration non-idempotent: a box with a different version
# rewrites files nobody touched and the `git diff --exit-code` idempotence
# check in the child plan's verification section fails for a reason unrelated
# to the spec.  Bump GENERATOR_VERSION and regenerate in the same commit.
#
# The generator version is not the only input: it runs post-generation hooks,
# and the `ruff` they invoke is the second one.  Those hooks are declared
# explicitly in scripts/openapi-python-client.yaml and scoped to the Python
# package, which keeps README.md out of the formatter's reach (recent ruff
# reformats Python code blocks inside Markdown; older ruff, and a box with no
# ruff at all, do not) -- see the note there.  The generated Python *is*
# formatted by ruff, and formatter output is a function of the ruff release:
# 0.9.1 (the repo's pre-commit pin) rewrites 215 of the modules 0.16.5 writes
# from the same spec.  So ruff is pinned exactly too -- RUFF_VERSION below and
# `ruff==` in the dev extra -- and checked the same way as the generator.
# Bump both pins and regenerate in the same commit.
#
# The pin is only a declaration; what checks it against the committed tree is
# tests/test_api_client_contract.py::
# test_generated_client_boilerplate_matches_what_the_pinned_generator_writes,
# which needs the generator installed.  Where it is not, the digests this
# script records in scripts/aq-client-boilerplate.sha256 check the same files
# from the checkout alone.
#
# The generated client lives in packages/aq-client/ and should be committed.
# After regenerating, reinstall it:
#   pip install -e packages/aq-client/

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
SPEC_FILE="$ROOT_DIR/openapi.json"
CLIENT_DIR="$ROOT_DIR/packages/aq-client"
API_URL="${AGENT_QUEUE_API_URL:-http://127.0.0.1:8081}"

# The exact openapi-python-client and ruff the committed packages/aq-client/
# tree was generated by.  See the note in the header before changing either.
GENERATOR_VERSION="0.29.0"
RUFF_VERSION="0.16.5"

if ! command -v openapi-python-client >/dev/null 2>&1; then
    echo "Error: openapi-python-client is not installed. Run: pip install 'openapi-python-client==$GENERATOR_VERSION'" >&2
    exit 1
fi

FOUND_VERSION="$(openapi-python-client --version | tr -d '\r' | awk '{print $NF}')"
if [[ "$FOUND_VERSION" != "$GENERATOR_VERSION" ]]; then
    echo "Error: openapi-python-client $FOUND_VERSION is installed but packages/aq-client/ is generated by $GENERATOR_VERSION." >&2
    echo "       Regenerating with another version rewrites the whole client tree (README.md included)." >&2
    echo "       Run: pip install 'openapi-python-client==$GENERATOR_VERSION'" >&2
    echo "       (Deliberately upgrading? Bump GENERATOR_VERSION in this script and commit the regenerated client with it.)" >&2
    exit 1
fi

# The generator only *warns* when a post hook's command is missing ("Skipping
# Integration: ruff is not in PATH") and still exits 0, so a box without ruff
# would quietly write an unformatted agent_queue_api_client/ and record its
# digests as canonical.  Fail instead.
if ! command -v ruff >/dev/null 2>&1; then
    echo "Error: ruff is not installed, and the generator's post hooks format the generated Python with it." >&2
    echo "       Without it the client would be regenerated unformatted. Run: pip install 'ruff==$RUFF_VERSION'" >&2
    exit 1
fi

# The hooks run whichever `ruff` shutil.which() finds, i.e. the first on PATH,
# so that is the one to check -- not `python -m ruff`.
FOUND_RUFF="$(ruff --version | tr -d '\r' | awk '{print $NF}')"
if [[ "$FOUND_RUFF" != "$RUFF_VERSION" ]]; then
    echo "Error: ruff $FOUND_RUFF is on PATH but packages/aq-client/ is formatted by ruff $RUFF_VERSION." >&2
    echo "       Formatter output is a function of the ruff release, so regenerating with another one" >&2
    echo "       rewrites generated modules openapi.json did not change." >&2
    echo "       Run: pip install 'ruff==$RUFF_VERSION'" >&2
    echo "       (Deliberately upgrading? Bump RUFF_VERSION in this script and 'ruff==' in pyproject.toml's dev extra," >&2
    echo "        then commit the regenerated client with them.)" >&2
    exit 1
fi

case "${1:-}" in
    --offline)
        # No daemon needed: create_app() builds the whole route surface from
        # the command registry, so the spec is a pure function of the
        # checkout.  This is what the drift guard in
        # tests/test_api_client_contract.py compares against.
        echo "Building OpenAPI spec offline from this checkout ..."
        (cd "$ROOT_DIR" && python -m src.api.spec "$SPEC_FILE")
        ;;
    --from-file)
        if [[ ! -f "$SPEC_FILE" ]]; then
            echo "Error: $SPEC_FILE not found. Run with --offline first." >&2
            exit 1
        fi
        echo "Using saved spec: $SPEC_FILE"
        ;;
    *)
        # The daemon serves the spec minified.  Writing that straight to
        # openapi.json produces a single-line, undiffable file that the drift
        # guard in tests/test_api_client_contract.py rejects, so render it
        # through the same src.api.spec writer --offline uses.  json parsing
        # happens before anything is written, so a failed fetch (pipefail is
        # on) leaves the existing openapi.json untouched.
        echo "Fetching OpenAPI spec from $API_URL/openapi.json ..."
        curl -sf "$API_URL/openapi.json" \
            | (cd "$ROOT_DIR" && python3 -m src.api.spec --stdin "$SPEC_FILE")
        ;;
esac

# Count paths in spec
PATHS=$(python3 -c "import json; print(len(json.load(open('$SPEC_FILE'))['paths']))")
echo "Spec has $PATHS paths"

# Remove old client and regenerate
if [[ -d "$CLIENT_DIR" ]]; then
    rm -rf "$CLIENT_DIR"
fi

# --config pins the package name: it would otherwise be derived from the
# spec's info.title ("Agent Q API" -> agent_q_api_client), renaming the
# package that src/cli/client.py imports by name.
openapi-python-client generate \
    --path "$SPEC_FILE" \
    --output-path "$CLIENT_DIR" \
    --config "$SCRIPT_DIR/openapi-python-client.yaml"
echo "Generated client at $CLIENT_DIR"

# Record the digests of the generator-only boilerplate.  The tree check in
# tests/test_api_client_contract.py can only run where the pinned generator is
# installed and skips everywhere else, so on a box carrying just the `cli`
# extra it is silently a no-op -- which is how a hand-edited README.md once
# landed with both the pin and that check already in place.  These digests let
# the same files be verified from the checkout alone, on every box.  Keep the
# list in step with _GENERATOR_BOILERPLATE in that test; it asserts they agree.
#
# The header names the tool versions the digests were recorded under.  It is
# what lets a checkout without the generator tell "the pins were bumped but
# the client was not regenerated" apart from "hand-edited": the digests test
# asserts the header agrees with the pins.  sha256sum -c ignores comment lines
# and the test's parser skips them, so the file still checks by hand.
DIGEST_FILE="$SCRIPT_DIR/aq-client-boilerplate.sha256"
{
    echo "# generated by openapi-python-client $GENERATOR_VERSION with ruff $RUFF_VERSION"
    cd "$CLIENT_DIR" && sha256sum \
        README.md \
        pyproject.toml \
        agent_queue_api_client/__init__.py \
        agent_queue_api_client/client.py \
        agent_queue_api_client/errors.py \
        agent_queue_api_client/types.py \
        agent_queue_api_client/py.typed
} > "$DIGEST_FILE"
echo "Recorded boilerplate digests at $DIGEST_FILE"

# Reinstall.  PEP 668 marks some interpreters externally managed; the client
# is a dev artifact, so fall back rather than failing the regeneration.
pip install -e "$CLIENT_DIR" --quiet \
    || pip install -e "$CLIENT_DIR" --quiet --break-system-packages \
    || echo "WARNING: could not pip install $CLIENT_DIR — install it manually" >&2
echo "Installed agent-queue-api-client"

echo "Done. Don't forget to commit packages/aq-client/, openapi.json and $DIGEST_FILE"
